### DISCUSSION TITLE
Use IDs in dashboards

### DISCUSSION THREAD

**Discussion by hialvaro** [OliveTin/OliveTin#421] [Q&A]
I have the following Olivetin config:

```yaml
actions:
    - title: "TEST IDS"
    entity: my_entity
    id: "raise_{{ my_entity.Id }}"
    shell: 'echo "hi"'

dashboards:
  - title: Test IDs
    contents:
      - title: TEST
        entity: my_entity
        type: fieldset
        contents:
          - title: "TEST IDS"
            id: "raise_{{ my_entity.Id }}"
```

I know this is not possible, but it would be great if we could have cleaner dashboards with a title set independently from an entity value. Right now, if the title is not different for each entity, it only renders the first one.

Is this possible right now? If not, wouldn't it be a nice-to-have?
