### DISCUSSION TITLE
Help with Dynamic Fieldsets for Managing LXC Containers

### DISCUSSION THREAD

**Discussion by Masked-Kunsiquat** [OliveTin/OliveTin#480] [Q&A]
# Description:

I'm trying to configure OliveTin to dynamically generate grouped fieldsets or individual sections for managing Proxmox LXC containers. My goal is to display details (e.g., name, VMID, status) for each container in an `entities` file (`lxc.yaml`) and include buttons for actions like `Start`, `Stop`, and `Reboot`. However, I haven't been able to get dynamic dashboards or fieldsets to work as intended.

---

# What I'm Trying to Achieve

1. Dynamic Grouping per Container:

A single dashboard that dynamically generates `fieldset` groups for each container defined in the `entities` file.

Each `fieldset` should:

- Display container-specific details (name, VMID, status).

- Include buttons (`Start`, `Stop`, `Reboot`) for executing container-specific commands.

2. Reusable and Clean Actions:

Define reusable actions for commands (`pct start`, `pct stop`, etc.) and reference them dynamically in `dashboards`.

3. Dynamic Dashboards or Fieldsets:

Dynamically generate individual dashboards or sections per container based on the entity data.

---

## What Works

The following configuration works to execute actions for the containers, but it doesn't behave dynamically or generate individual fieldsets or dashboards for each container. The `dashboards` section doesn’t seem to affect functionality and can even be omitted without impacting the behavior.

```yaml
actions:
  - title: Start {{ lxc.name }}
    shell: pct start {{ lxc.vmid }}
    entity: lxc

  - title: Stop {{ lxc.name }}
    shell: pct stop {{ lxc.vmid }}
    entity: lxc

  - title: Reboot {{ lxc.name }}
    shell: pct reboot {{ lxc.vmid }}
    entity: lxc

entities:
  - file: /etc/OliveTin/entities/lxc.yaml
    name: lxc

dashboards:
  - title: LXC Containers
    contents:
      - title: 'Manage {{ lxc.name }} (VMID: {{ lxc.vmid }})'
        entity: lxc
        type: fieldset
        contents:
          - title: 'Start {{ lxc.name }}'
          - title: 'Stop {{ lxc.name }}'
          - title: 'Reboot {{ lxc.name }}'
```
### Behavior:

- All containers are presented in a single dashboard with ungrouped buttons.

- The `dashboards` section doesn't appear to dynamically render placeholders like `{{ lxc.name }}` or `{{ lxc.vmid }}`.

- Removing the `dashboards` section entirely doesn't change the behavior.

---

## What Fails

The following configuration attempts to dynamically generate fieldsets for each container using placeholders like `{{ lxc.name }}` and `{{ lxc.vmid }}`, but OliveTin fails to start with the error: `Config unmarshal error: invalid keys`.

```yaml
actions:
  - title: Start LXC
    shell: pct start {{ lxc.vmid }}
    entity: lxc

  - title: Stop LXC
    shell: pct stop {{ lxc.vmid }}
    entity: lxc

  - title: Reboot LXC
    shell: pct reboot {{ lxc.vmid }}
    entity: lxc

entities:
  - file: /etc/OliveTin/entities/lxc.yaml
    name: lxc

dashboards:
  - title: LXC Containers
    contents:
      - title: "{{ lxc.name }} (VMID: {{ lxc.vmid }})"
        entity: lxc
        type: fieldset
        contents:
          - type: display
            title: "**Status**: {{ lxc.status }}"
          - type: button
            title: "Start {{ lxc.name }}"
            action: Start LXC
          - type: button
            title: "Stop {{ lxc.name }}"
            action: Stop LXC
          - type: button
            title: "Reboot {{ lxc.name }}"
            action: Reboot LXC
```

---

## Entity File Example

Here's the `entities` file I'm using:

```yaml
- vmid: 101
  name: container1
  status: running

- vmid: 102
  name: container2
  status: stopped

- vmid: 103
  name: container3
  status: stopped
```

---

## Observations

1. Dynamic Fieldsets Fail:

Placeholders like `{{ lxc.name }}` or `{{ lxc.vmid }}` are not resolving dynamically, and OliveTin fails to start.

2. Dashboards Section Can Be Omitted:

The `actions` section works independently of the `dashboards` section.

Omitting dashboards still allows the `actions` to execute, but the UI becomes flat and cluttered.

3. Dynamic Dashboards Are Unclear:

It's not clear if OliveTin supports fully dynamic dashboards or fieldsets for entities.

---
# Request for Help

1. How can I dynamically create `fieldsets` or grouped sections for each container using placeholders like `{{ lxc.name }}` and `{{ lxc.vmid }}`?

2. Should I be using a different approach to dynamically render buttons and details per container?

3. Is there a working example of using `fieldsets` with dynamic placeholders for entity data?

Any guidance, working examples, or suggestions would be greatly appreciated! 😁
