### DISCUSSION TITLE
help to config dual dashboards: guests and admin (with pwd)

### DISCUSSION THREAD

**Discussion by posta246** [OliveTin/OliveTin#608] [Q&A]
Hi,
I'm trying to config an "easy" dual dashboards container, where a dashboard should be always visible for any users (the guests), why the other one is for the admin only. Actions work. I read and apply the doc "Example: Some actions require admin" but I cannot do it work.
I've tried lot of combo based on the docs, but the following config files does not work as expected.
(note: I will open a new discussion because in the docs there are some info misleading, I think).
Thanks a lot to everybody could help me, I lost half on my mind on it...

```
# ==========================================================
#                               GENERAL AND SECURITY SECTION
# ==========================================================

listenAddressSingleHTTPFrontend: 0.0.0.0:1337

# Choose from INFO (default), WARN and DEBUG
logLevel: "INFO"

# the doc says the following line is needed 
# but there is not in the example. I think it 
# is a paste and copy error and you dont need it
#authRequireGuestsToLogin: true

accessControlLists:
  - name: "noguests"
    permissions:
      view: false
      exec: false
      logs: false
    matchUsernames: [ "guest" ] # in some part of docs it is "matchUserNames"

  - name: "admins"
    permissions:
      view: true
      exec: true
      logs: true
    matchUsergroups: [ "admins" ]

authLocalUsers:
  enabled: true
  users:
    - username: "admin"
      usergroup: admins
      password: $argon2id$blablablablabla...

# ==========================================================
#                                            ACTIONS SECTION
# ==========================================================

# Actions (buttons) to show up on the WebUI:
actions:

# ----------------------------------------
#  GUEST | STOP DOWNLOAD STACK
# ----------------------------------------
- title: stop download_stack
  icon: stop
  shell: ssh root@172.16.1.1 'download_stack-stop'

# ----------------------------------------
#  GUEST | START DOWNLOAD STACK
# ----------------------------------------
- title: start download_stack
  icon: start
  shell: ssh root@172.16.1.1 'download_stack-up'

# ----------------------------------------
#  ADMIN | START BACKUP SERVER
# ----------------------------------------
- title: start proxmox backup server
  icon: start
  acls:
    - noguests
    - admins
  shell: ssh root@172.16.1.1 'start_proxmox_backup_server'

# ----------------------------------------
#  ADMIN | STOP USB DISKS AND RELATED THINGS
# ----------------------------------------
- title: stop usb disks and related things
  icon: stop
  acls:
    - noguests
    - admins  
  shell: ssh root@172.16.1.1 'stop-disks-usb-related-things'

# ----------------------------------------
#  ADMIN | STOP ALL CONTAINERS
# ----------------------------------------
- title: stop all containers
  icon: stop
  acls:
    - noguests
    - admins
  shell: ssh root@172.16.1.1 'stop-all-containers'

# ----------------------------------------
#  ADMIN | START ALL CONTAINERS
# ----------------------------------------
- title: start all containers
  icon: start
  acls:
    - noguests
    - admins
  shell: ssh root@172.16.1.1 'start-all-containers'

# ----------------------------------------
#  ADMIN | STOP SELECTED CONTAINER
# ----------------------------------------
- title: stop docker container
  icon: stop
  shell: ssh root@172.16.1.1 '{{ container }}-stop'
  acls:
    - noguests
    - admins
  arguments:
    - name: container
      title: Container name
      choices:
        - value: jellyfin
        - value: plex 
        - value: usememos
        - value: scrutiny

# ----------------------------------------
#  ADMIN | RESTART SELECTED CONTAINER
# ----------------------------------------
- title: restart docker container
  icon: restart
  shell: ssh root@172.16.1.1 '{{ container }}-restart'
  acls:
    - admins  
  arguments:
    - name: container
      title: Container name
      choices:
        - value: jellyfin
        - value: plex
        - value: usememos
        - value: scrutiny

# ==========================================================
#                                         DASHBOARDS SECTION
# ==========================================================
dashboards:
  - title: Guest Dashboard
    contents:
      - title: stop download_stack
      - title: start download_stack

  - title: Admin Dashboard
    contents:
      - title: start proxmox backup server
      - title: stop usb disks and related things
      - title: stop all containers
      - title: start all containers
      - title: stop docker container
      - title: restart docker container

```
