### ISSUE TITLE
Allow both drop down and text box for user input for the same button

### ISSUE THREAD

**Issue by qazero** [OliveTin/OliveTin#103]
**Is your feature request related to a problem? Please describe.**
I would like to create 1 button which allows the user to either choose from the predefined dropdown list or type their own input into the box. Please see the screenshot below as an example.

![image](https://user-images.githubusercontent.com/10906010/216793500-787ef89a-d649-4556-9385-f516458b0ded.png)

**Describe the solution you'd like**
The above screenshot was generated using the following config:

```yaml
- title: Autoscan
  shell: ssh -i /home/olivetin/.ssh/id_rsa seed@server -p 22 "/opt/configs/scan.sh \"{{ path }}\""
  timeout: 30
  arguments:
    - name: path
      title: Path
      type: very_dangerous_raw_string
      default: blah
    - name: path
      choices:
        - title: Path
          value: path
```

However, when I try and enter something in the text box and click on the start button, I get the following error:

```
stdout
path parameter is empty!

stderr
exit status 1
```

Strangely the dropdown options execute just fine. And if I remove the dropdown choices altogether then the text box works fine. It looks like OliveTin does not support having both on the same button? If so could you please add this feature?
