### ISSUE TITLE
Two new argument types: checkbox and checklist

### ISSUE THREAD

**Issue by ManuelFte** [OliveTin/OliveTin#104]
I would like to suggest the addition of two new argument types which would be a checkbox and a list of checkboxes. These would be useful for functions that require verification or when the user can select several options rather than picking just one from a drop down menu.

I imagine that they could work like this:

# checkbox

Returns a boolean. An example could be a button that reboots the server and where the checkbox prevents accidental clicks:

![image](https://user-images.githubusercontent.com/68722732/217682337-dc499dbe-7cdb-4cef-b722-23622d8ac04f.png)

```yaml
- title: Reboot server
  icon: "⏻"
  shell: <code here>
  arguments:
    - title: Are you sure?
      name: verification
      type: checkbox
```

# checklist

Returns an array of the options chosen. An example could be a backup script that allows you to choose the directories you want to back up:

![image](https://user-images.githubusercontent.com/68722732/217677290-2377166c-d080-404b-88b2-b3c61899fd7f.png)

```yaml
- title: Backup Script
  icon: "💾"
  shell: <code here>
  arguments:
    - title: Directories to back up
      name: directories
      type: checklist
      choices:
        - title: Documents
          value: documents

        - title: Photos
          value: photos

        - title: Music
          value: music
    
        - title: Videos
          value: videos
```

**Comment by jamesread** [comment]
Hey @ManuelFte , 

Thanks for taking the time to write this up, and for investigating the extra effort for the examples - love that! 

Let's coktijuecuour ideas into the design. I think we could break this design into a few types as you're alluding to; 

- checkbox - simply gives 1 / 0 depending on checked / unchecked. It could also be true / false - but 1 / 0 would be easier for bash scripts and any other language, rather than having to parse the text.
- confirmation - this has come up before, it's more like a "dummy" argument that has to be ticked before OliveTin will execute the action. It's value when executed would always be 1 (and if it's unticked, execution should be cancelled with a logged error). 
- checklist - your proposal is fine, but we need to think about the format of the values passed through to any script; probably CSV makes the most sense here - "Apple, Chocolate Cake,Waffles". This is probably easily parsed by most languages. You'd refer to the value on the shell argument like: `script.sh {{myChecklist}}`

I can't think of any other design considerations right now, what do you think?

**Comment by ManuelFte** [comment]
For the boolean, 1/0 definitely sounds better than true/false as strings.

What would be the difference between `checkbox` and `confirmation`?

CSV also sounds fine as the format for the array.

I have no more recommendations, happy to hear that this seems to be very smooth.

**Comment by jamesread** [comment]
> What would be the difference between checkbox and confirmation? 

`checkbox` would allow you to refer to values in the shell command; eg: {{ runAsRoot }}, or {{ hasTimer }}, whereas `confirmation` would be a special argument type that stops the execution entirely unless ticked. 

> Edit: actually, I just thought on a suggestion: for the checklist, maybe an option to select all/select none would be a plus.

This sounds sensible :-) 

---

Now that I think the design looks complete, I'm going to try and capture these design choices as some sort of acceptance criteria for this feature. I've not done that before, but I think that's how we should be implementing features / changes in OliveTin. This is a nice small feature to test that out on :-)

**Comment by ManuelFte** [comment]
> `checkbox` would allow you to refer to values in the shell command; eg: {{ runAsRoot }}, or {{ hasTimer }}, whereas `confirmation` would be a special argument type that stops the execution entirely unless ticked.

Ohh, I get it. So in the practice, `confirmation` would be what you'd use for my example of the reboot button that requires verification or else the script won't run, while `checkbox` would be used when the script does run but it has to check if the user selected certain options.

Sounds good, it's a built-in feature to accomplish tasks like that of the example without having to write a function that does the verification, and that for shell instructions that are just one-liners it'd be ugly (the verification would be longer than the actual command, lol).

> Now that I think the design looks complete, I'm going to try and capture these design choices as some sort of acceptance criteria for this feature. I've not done that before, but I think that's how we should be implementing features / changes in OliveTin. This is a nice small feature to test that out on :-)

Nice, glad that my suggestion was useful for this, hahaha. Looking forward to see the feature.

**Comment by jamesread** [comment]
Just had a thought, it may be nice to be able to set string values; 

```
actions:
  - title: remove files
    shell: rm {{ useForce }} /mnt/Downloads/
    arguments:
      - name: useForce
        type: checkbox
        valueIfChecked: "-rf"
```
