### ISSUE TITLE
Creation of an addditional ACL attribute regarding the viewing of logs.

### ISSUE THREAD

**Issue by saulchristie** [OliveTin/OliveTin#135]
**Is your feature request related to a problem? Please describe.**
When restricting view/exec permissions using ACLs in a multiuser environment users are still able to view the logs of all actions irrespective of their view/exec permission.

**Describe the solution you'd like**
I propose the creation of an additional ACL operator, `logs`, functionally similar to that of the `view` and `exec` but referring to whether the log output of an action can seen members of the ACL.

**Describe alternatives you've considered**
None.

**Additional context**
If implemented, the following hypothetical config would allow members of 'ops' to only see the log output of actions they have been granted via the `ops` ACL and nothing more:

```
defaultPermissions:
  view: false
  exec: false
  logs: false
 
accessControlLists:
- name: ops
  matchUsernames:
  - operator1@example.com
  - operator2@example.com
  permissions:
    view: true
    exec: true
    logs: true
```
