### ISSUE TITLE
Issue with multiple dropdown arguments

### ISSUE THREAD

**Issue by mcmiv413** [OliveTin/OliveTin#169]
If I try to provide 2 dropdowns in an action, the first drop down combines the options for both drop downs. And the name list for both dropdowns is the name of the second drop down:

![image](https://github.com/OliveTin/OliveTin/assets/8952154/0e355c8a-61a8-44be-b47e-c8b256336a74)

**To Reproduce**
My config:
```
   - title: Container Actions
     icon: smile
     shell: ssh user@host 'docker {{ command }} {{ container }}'
     timeout: 60
     arguments:
       - name: command
         choices:
          - title: Stop
            value: stop

          - title: Start
            value: start

          - title: Restart
            value: restart

       - name: container
         choices:
          - title: Containera
            value: containera

          - title: Containerb
            value: containerb

          - title: Containerc
            value: containerc

```
**Expected behavior**
I would expect 2 drop downs with independent dropdown lists.
