### ISSUE TITLE
wake on lan

### ISSUE THREAD

**Issue by itssenna** [OliveTin/OliveTin#194]
I run olivetin inside a docker container on a raspberry pi. and I want to use it to turn on devices when im not home. but what do I need to type in mine config.yaml to make this work.

**Comment by zilch-gg** [comment]
You need to set the container network to "host" in the docker-compose.yml:

```
version: "3.8"
services:
  olivetin:
    container_name: olivetin
    image: jamesread/olivetin
    network_mode: host # web ui port: 1337/tcp
    volumes:
      - /docker/OliveTin:/config # replace host path or volume as needed
    restart: unless-stopped
```
