### ISSUE TITLE
titleAlias is not working in config.yaml

### ISSUE THREAD

**Issue by vutsalsinghal** [OliveTin/OliveTin#200]
Hi I'm using OliveTin via docker (image: jamesread/olivetin:2023.03.25)

My config.yaml file is
```
listenAddressSingleHTTPFrontend: 0.0.0.0:1337 

logLevel: "INFO"
showFooter: false
actions:
  - title: Stop Ollama
    titleAlias: stop_ollama
    icon: '&#127912;'
    shell: |
        cat <<EOT > /host/my_pipe
        printf "\n######################## Exec from OliveTin - Bing Delete Last - $(date) ########################\n"
        docker -H 192.168.0.81:31023 stop ollama_container
        echo "Stopped Ollama!"
        EOT
    timeout: 10
```

The above works as expected if `titleAlias: stop_ollama` is commented but when I uncomment, the following error in seen in the logs

```
level="error" msg="Config unmarshal error 1 error(s) decoding:\n\n* 'actions[0]' has invalid keys: titlealias"
```
Does it has something to do with `titleAlias` <-> `titlealias` ?

---

My docker-compose is as follows
```
########################################
### Olivetin - UI for scripts
########################################
  olive:
    image: jamesread/olivetin:2023.03.25
    container_name: olive_container
    user: root
    privileged: true
    ports:
      - 21010:1337
    volumes:
      - ./olive:/config
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro # for timezone
    mem_limit: 300m
    networks:
      - apps_ntwrk
    restart: unless-stopped
```
