### ISSUE TITLE
Running commands as local user

### ISSUE THREAD

**Issue by LordZeuss** [OliveTin/OliveTin#210]
**What seems to be the problem?!**

When I am running a shell command, it does not seem to be running as a local user at all, even if docker environment is added with correct PGID and PUID. Details at the end.

If you are getting an error message, then please copy/paste, or better, provide
a screenshot to show us exactly what is wrong.

N/A

**What package/file/container did you use to install OliveTin?**

The most recent docker image. Fresh Install.

eg: OliveTin-1234-x86_64.rpm
eg: Container from Dockerhub - please include the version number

**Your config.yaml**

```
#USING BASH ALIAS
actions:
  - title: Run my script
    shell: run-script
```
OR
```
# USING REG SHELL
actions:
 - title: Run my script shell
   shell: cd /home/user/test && ./myscript.sh
```

**docker-compose.yml** for extra troubleshooting:

```
version: "3.8"
services:
  olivetin:
    container_name: olivetin
    image: jamesread/olivetin
    volumes:
      - /home/user/olivetin:/config
    ports:
      - 1337:1337
    restart: unless-stopped

networks:
  web:
      external: true
```

**OliveTin logs**

N/A as there is no "true" error

**Anything else?**

## DETAILS:

Lets say I have a shell command that is the following: cd /home/user/test && ./myscript.sh

The command will fail because /home/user/test directory is not found. (Error 127)

Okay, what if I setup a bash alias for my local user to do that, so I just have to type in 'run-script' into the terminal and it will do the above command since its an alias?

Error 127: run-script command not found

If I want to do these types of commands, is it possible? Am I doing something wrong?

Any help would be very much appreciated. Thanks!

**Comment by jamesread** [comment]
Heya, it looks like you broadly have two issues here. 

Firstly, OliveTin doesn't use PGID and PUID, see the explanation here; https://docs.olivetin.app/no-puid-pgid.html

Secondly, it looks like your script os on your hoke directory, and OliveTin is running as a container. If you want to use that script, you have three options: 

A) ssh back into your host  https://docs.olivetin.app/action-ssh.html

B) mount your home directory into OliveTin so it can use the script. This isn't going to work though if the script needs other files on your filesystem. (Eg, of the script works on files in /opt - unless you mount that too!)

C) Don't use docker, and just run as a native Linux service that can see your whole filesystem.

**Comment by LordZeuss** [comment]
> Heya, it looks like you broadly have two issues here. 
> 
> Firstly, OliveTin doesn't use PGID and PUID, see the explanation here; https://docs.olivetin.app/no-puid-pgid.html
> 
> Secondly, it looks like your script is in on your home directory, and OliveTin is running as a container. If you want to use that script, you have three options: 
> 
> A) ssh back into your host  https://docs.olivetin.app/action-ssh.html
> 
> B) mount your home directory into OliveTin so it can use the script. This isn't going to work though if the script needs other files on your filesystem. (Eg, of the script works on files in /opt - unless you mount that too!)
> 
> C) Don't use docker, and just run as a native Linux service that can see your whole filesystem. 

This makes sense. Thanks for the details?

How would my config.yaml need to look if I made this change?

Lets say I add the following mount point to the docker-compose.yml file as a mount point:

```
- /home/user/test:/testfolder
```
then in the config.yaml:

```
shell: cd testfolder && ./myscript.sh
```
OR
```
shell: cd /testfolder && ./myscript.sh
```

Would this be correct? I seem to be getting an issue still where it is not finding the directory when I try to "cd" into it to run the script, but maybe that is due to my own error.

Thanks for the help!

**Comment by jamesread** [comment]
So, simply do this:

```yaml
actions: 
  - title: my script
    shell: /testfolder/myscript.sh

```
