### ISSUE TITLE
How to handle ssh Passphrases

### ISSUE THREAD

**Issue by madhur** [OliveTin/OliveTin#218]
**What seems to be the problem?!**

I am running OliveTin as a LXC in Proxmox. I want to run commands in Proxmox host itself.

Hence I am ssh into the host. However, it asks for the ssh passphrase. I am not sure how this can be automated using an action.

```
Enter passphrase for key '/root/.ssh/id_rsa': 
Linux pve 6.5.11-4-pve #1 SMP PREEMPT_DYNAMIC PMX 6.5.11-4 (2023-11-20T10:19Z) x86_64

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Sat Jan 27 10:32:00 2024 from 192.168.100.27
root@pve:~# 
```

**Can you provide a sosreport?**

A sosreport really helps us to help you, by providing critical information about your install. If you can generate a sosreport, please copy and paste the output here.

How to generate a sosreport: 

**What package/file/container did you use to install OliveTin?**

Installed the latest deb file via https://github.com/tteck/Proxmox/blob/main/misc/olivetin.sh

**Your config.yaml**
```
# Listen on all addresses available, port 1337
listenAddressSingleHTTPFrontend: 0.0.0.0:1337

# Choose from INFO (default), WARN and DEBUG
logLevel: "INFO"

# Actions (buttons) to show up on the WebUI:
actions:
- title: Shutdown
  shell: shutdown
  popupOnStart: true

  # This will run a simple script that you create.
- title: Start Redis
  shell: pct start 107;pct start 108;pct start 109;
  #shellAfterCompleted: "apprise -t 'Notification: Backup script completed' -b 'The backup script completed with code {{ exitCode}}. The log is: \n {{ stdout }} '"
  maxConcurrent: 1
 
 
- title: Start cassandra
  shell: pct start 110

- title: Start kafka
  shell: pct start 105

- title: start zookeeper
  shell: pct start 103

- title: Start cassandra, zk , kafka, redis
  shell: ssh root@192.168.100.128 'pct start 107;pct start 108; pct start 109; pct start 110; pct start 105; pct start 103;'
  shellAfterCompleted: "curl -d 'Started' https://ntfy.madhur.co.in/shell"
```

**OliveTin logs**

If possible, please copy and paste your OliveTin logs from when the error happened.

**Screenshot of WebDeveloper console logs**

![image](https://github.com/OliveTin/OliveTin/assets/509431/83949c5b-a8ea-48a8-a15c-dcd51dd92164)

**Anything else?**
