### ISSUE TITLE
Allow int range for choices and allow title to = value

### ISSUE THREAD

**Issue by kevev** [OliveTin/OliveTin#237]
I have a huge range of digits that I would like to add easily to a "choices" input. Instead of doing like so:

choices:
  - title: "0001"
  - value: "0002"
  ..........
  - title: "9998"
  - value: "9998"

Maybe something like:
- title-range: "0001" - "9998

**Comment by kevev** [comment]
Or even better, a way to store a range in a var that can be used in the config for multiple buttons. :)

**Comment by jamesread** [comment]
Would you really want 1000 items in a dropdown checkbox, labeled 0001 to 9999, or would a text inbox box that validates the value 0001 to 9999 also work for you?

**Comment by kevev** [comment]
Sorry, that was a crappy example. Currently 40.

**Comment by jamesread** [comment]
Are the digits always going be sequential? 

Loke 5000-5040?

**Comment by kevev** [comment]
Yes.

**Comment by jamesread** [comment]
I've tried to do this with regex, but it's kind of gross.

I've thought about adding a native "number" input type, but this requires adding "min" and "max" to all argument types, and that doesn't feel right. 

It's likely that people in the future would want something like "allow 100-150, but not 150-199, but also 200+", and a simple min/max doens't help here.

So I figure you're probably typed out all the codes now, so the main problem you have is that this makes your config.yaml really "messy"? If that is the main problem that we're dealing with in this feature request, then I think we have an option - using entities. 

This was recently added, and is documented here; https://docs.olivetin.app/arg-dropdowns.html#args-dropdown-entities

@kevev , what this would mean would still be a dropdown selection, and it would still mean adding entries manually in a file, but at least it would not make your config file messy, which is what I think you want to avoid?

Try this; 

**config.yaml**
```yaml
actions:
  - title: Enter Code
    shell: echo {{ selected_code }}
    arguments:
      - name: selected_code
        entity: code
        choices:
          - value: '{{ code.value }}'
            title: '{{ code.value }}'

entities: 
  - file: entities/codes.yaml
    name: code
```

**entities/codes.yaml**
```
- value: 0001
- value: 0002
- value: 0003
...
- value: 3999
- value: 4000
```
