### ISSUE TITLE
`dnf install` should be run as supeuser inside container

### ISSUE THREAD

**Issue by inknos** [OliveTin/OliveTin#28]
**Describe the bug**
When trying to install `docker` inside olivetin it is not possible due to lack of superuser permissions.

**To Reproduce**
1. Install olivetin using dockerfile
2. Perform additional steps for [docker](https://docs.olivetin.app/action-container-control.html). (Tweaked the dockerfile instead)
2. run `docker exec -it olivetin dnf install -y docker`
  `Error: This command has to be run with superuser privileges (under the root user on most systems).`
or
3. run `docker exec -it olivetin sudo dnf install -y docker`
  `[sudo] password for olivetin:`

**Expected behavior**
Should install `docker`

**Additional context**
```
dockerfile
---
version: "2.1"
services:
  olivetin:
    container_name: olivetin
    image: jamesread/olivetin 

    volumes:
      - /srv/dev-disk-by-uuid-d2287285-5827-439a-bc32-7c8ad314eacf/Config/OliveTin:/config:ro
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "1337:1337"
    restart: unless-stopped
```
Running inside Portainer 2.6.1 on Openmediavault 5.6.7-1
```
$ uname -a
Linux rockpi 5.10.35-rockchip64 #21.05.1 SMP PREEMPT Fri May 7 13:53:11 UTC 2021 aarch64 GNU/Linux
```

**Suggestion:**
If you don't want to run the container as `root`, what about adding something like `olivetin     ALL=(ALL)       /usr/bin/dnf` in `/etc/sudoers`?
