### ISSUE TITLE
Dropdown list with entity not working after update to 2024.04.021

### ISSUE THREAD

**Issue by ENgraver666** [OliveTin/OliveTin#285]
**Describe the bug**
When i'm using the dropdown list with entries from an entity it's only showing a textbox. This was working perfectly fine with version 2024.04.018.

**To Reproduce**
My config.yaml
```
actions:
  - title: Start Docker
    popupOnStart: execution-dialog-stdout-only
    shell: docker start {{container}}
    arguments:
      - name: container
        entity: docker_list 
        title: Container name
        choices:
          - value: '{{ docker_list.Name }}'
            title: '{{ docker_list.Display }}'

entities:
  - file: /etc/OliveTin/entities/docker_list.json
    name: docker_list
```

My docker_list.json

```
{"Name":"Test1","Display":"First Container"}
{"Name":"Test2","Display":"Second Container"}
```

**Expected behavior**
Showing a dropdown list instead of a textbox.

**Screenshots**
![Screenshot from 2024-04-21 20-59-22](https://github.com/OliveTin/OliveTin/assets/50297221/67584b71-6b3c-48a6-ab7c-a321422eddad)
