### ISSUE TITLE
Authorization / Permissions support 

### ISSUE THREAD

**Issue by jamesread** [OliveTin/OliveTin#30]
Many users seem to want to restrict actions to authorized users, before they access OliveTin. This is an early design draft for Authorization / Permissions checks in OliveTin. 

Because of the many, many ways to authenticate users, this is just too much code to handle right now (Active Directory, Login with Google OpenID, plain username/password), etc. However, many "reverse proxies" (which I prefer to call load balancers), like Traefik, like Nginx, etc, all are able to handle this now-a-days, massively simplifying this for application owners, by supporting Forward Auth. Therefore, OliveTin itself will not support actual Authentication of users for now - let's try Authorization using this load balancer method as a first step. 

Here's how it should work; Image shamelessly "borrowed" from Traefik's [docs on forward auth;](https://doc.traefik.io/traefik/middlewares/http/forwardauth/)

![image](https://user-images.githubusercontent.com/2025715/143313815-142be518-2528-4596-960b-a5d6936c1e83.png)

1. The load balancer should configure OliveTin's frontend as a "protected" / Authenticated endpoint.
2. If login is needed, the load balancer should do it's Auth magic.
3. When authed, the load balancer should set the X-Auth-User header when making requests to OliveTin.
4. OliveTin trusts the X-Auth-User, and uses the "username" to control access to actions.
5. OliveTin uses this username when checking permissions before viewing/executing actions. 

Even today, OliveTin already supports user-based permissions controls - however, it currently treats all users as guests. You can view all the permissions checks if you turn on DEBUG logging (it's a bit verbose, though!)

This is the current config syntax, still in design phase. 

````
defaultPermissions:
  view: false
  exec: false

usergroups:
  - name: devops
      - alice
      
  - name: servicedesk
    members:
      - bob
      - charles

actions:
  - title: Reboot server
    shell: reboot     
    permissions:
      - usergroup: devops
        exec: true

  - title: Restart apache
    shell: service httpd restart
    permissions: 
      - usergroup: devops
        exec: true
      - usergroup: servicedesk
        exec: true
````

Comments about this feature and it's design are most welcome from the community, if you think this design looks good or this feature looks useful to you then a :+1: on this issue would be helpful too for prioritization.
