### ISSUE TITLE
How to use control docker containers via docker compose, inside the olivetin container

### ISSUE THREAD

**Issue by nickelswitte** [OliveTin/OliveTin#312]
**What seems to be the problem?!**

I run all my services on my host machine using docker compose. In one case, a minecraft server. I would like to give others safe access to start and stop this server. I use olivetin inside a docker container itself. Somehow I cannot currently figure out, how to control docker containers on my host machine, from within the olivetin container. Here are my steps:

1. I have the following docker compose file for olivetin:
```
services:
  olivetin:
    container_name: olivetin
    image: jamesread/olivetin
    volumes:
      - ./config:/config # replace host path or volume as needed
      - /var/run/docker.sock:/var/run/docker.sock
    #ports:
    #  - "1337:1337"
    restart: unless-stopped
    user: root
    privileged: true
```
2. I managed to install docker compose inside the olivetin container (with the help from [89](https://github.com/OliveTin/OliveTin/issues/89), although only until I restart the olivetin container, then it is lost again).
3. I defined the following action:
```
  - title: Start Minecraft Server
    icon: restart
    shell: docker compose -f /home/myuser/apps/minecraft/docker-compose.yml up -d
``` 
5. Other actions work well (e.g. ping, disc usage, etc.) but this one throws and error:
```
olivetin  | level="info" msg="Action finished" actionTitle="Start Minecraft Server" exit="14" stderr="stat /home/myuser/apps/minecraft/docker-compose.yml: no such file or directory\n" stdout="" timedOut="false"
```

It has not access to the docker compose file, as this one is on the host machine, and not in the olivetin container. But I am a bit confused. I run services like portainer, and am used to them controlling my other docker containers via the `/var/run/docker.sock` bind mount. However, when I follow the docs of olivetin, it rather seems like I am supposed to run docker _within_ the olivetin container, and not on my host machine. Or I am not understanding something here.

So I guess the question is: How can I control containers on my host machine with `docker compose` correctly? 

**Can you provide a sosreport?**
```
Build:
commit: c4d1a2a
version: 2024.03.24
date: \"2024-03-24T23:06:37Z\"

# Runtime:
os: linux
osreleaseprettyname: PRETTY_NAME=\"Fedora Linux 38 (Container Image)\"
arch: amd64
incontainer: true
lastbrowseruseragent: \"\"

# Config:
countofactions: 21
countofdashboards: 2
loglevel: INFO
listenaddresssinglehttpfrontend: 0.0.0.0:1337
listenaddresswebui: localhost:1340
listenaddressrestactions: localhost:1338
listenaddressgrpcactions: localhost:1339
timezone: Local
```

**What package/file/container did you use to install OliveTin?**

official latest tag, so I guess  OliveTin-1234-x86_64.rpm

**Your config.yaml**

```
everything is default
```
