### ISSUE TITLE
Run python script on the host from OliveTin Docker container

### ISSUE THREAD

**Issue by marcolino7** [OliveTin/OliveTin#313]
Hi,
I am running OliveTin on docker on RaspberryPI 4, and I need to provide a Web User Interface to some python script that contron Raspi GPIO. Python script is on the host where docker run. Is there a way to achieve this with OliveTin?

Many Thanks

Marco

**Comment by jamesread** [comment]
Hey @marcolino7 , so sorry that you've been waiting soong for a reply. Sp yes, generally when this comes up, SSH is the best option to get back to yoir host: 

https://docs.olivetin.app/action-ssh.html

**Comment by lukedoomer** [comment]
what if we have to append parameters for the script with quote and double quote like this?


the original shell command
```
actions:
  - title: test
    shell: >
      ssh user@10.0.0.1 ./script.sh 'https://foo.com/bar' '"m_promo_no":"U94060100006","dt_promo_no":"D94060100001","gift_code":""'
```
olivetin  | level="info" msg="Action parse args - Before" actionTitle="promoMechReg" cmd="ssh user@10.0.0.1 ./script.sh 'https://foo.com/bar' '\"m_promo_no\":\"U94060100006\",\"dt_promo_no\":\"D94060100001\",\"gift_code\":\"\"'\n"
olivetin  | level="info" msg="Action parse args - After" actionTitle="promoMechReg" cmd="ssh user@10.0.0.1 ./script.sh 'https://foo.com/bar' '\"m_promo_no\":\"U94060100006\",\"dt_promo_no\":\"D94060100001\",\"gift_code\":\"\"'\n"
```

**Comment by jamesread** [comment]
@lukedoomer You should encapsulate it all as one quoted string, like this;

```yaml
actions:
  - title: test
    shell: >
      ssh user@10.0.0.1 "./script.sh 'https://foo.com/bar' 'm_promo_no':'U94060100006','dt_promo_no':'D94060100001','gift_code':''"
```
