### ISSUE TITLE
server.yaml has invalid keys: maxrate

### ISSUE THREAD

**Issue by nickelswitte** [OliveTin/OliveTin#314]
**Describe the bug**
I am trying to use the maxrating, as documented [here](https://docs.olivetin.app/ratelimits.html), but olivetin does not recognize this key. The error message is:
```
"Config unmarshal error 1 error(s) decoding:\n\n* 'actions[14]' has invalid keys: maxrate"
```

The action is
```
  - title: Minecraft Info
    icon: start
    maxRate:
      - limit: 1
        duration: 1m
    shell: docker exec minecraft-server rcon-cli list
    timeout: 5
    maxConcurrent: 1
    popupOnStart: execution-dialog-stdout-only
```

**To Reproduce**
Set this action in server.yaml
Click on action

**Expected behavior**
That the maxrate works, like in the docs.
