### ISSUE TITLE
How to show a clickable link on execution?

### ISSUE THREAD

**Issue by papampi** [OliveTin/OliveTin#315]
I have a program that on every restart creates a secret for its webui and does not have setting to set a static key and output the key in its log file.
I have written a script to extract the key file and echo link to the program webui like this:

```http://192.168.1.10:9856/ui/?secret=qY2yQHvhMkwhb80s```

I added an action in Olivetin to run the bash script and echo the link:
```
- title: MyApp Web
  shell: bash /path_to_script/script.sh        
  popupOnStart: execution-dialog-stdout-only
  icon: <iconify-icon icon="carbon:gui"></iconify-icon> 
```
  
It shows the link with no problem but cant find a way to make it show a clickable link so I can just click it instead of select and open it in new tab.

Is there anyway to do it?

**Comment by jamesread** [comment]
Heya @papampi , sorry for the wait, my free coding time has been taken up on other projects recently.

Yep, you can show a clickable link if you write the link to a temporary entity file, and then show it in a display;

```yaml
actions:
  - title: get link
    shell: "echo '- link: google.com' > /tmp/link.yml"

entities:
  - file: /tmp/link.yml
    name: linkfile

dashboards:
  - title: "test"
    contents:
      - title: "Link"
        type: fieldset
        entity: linkfile
        contents:
          - title: |
              <a href = "{{ linkfile.link }}">{{ linkfile.link }}</a>
            type: display

          - title: get link
```
