### ISSUE TITLE
Updates of an entity file do not trigger a refresh of the web interface

### ISSUE THREAD

**Issue by ioqy** [OliveTin/OliveTin#316]
**Describe the bug**
When I update an entity file, either via an action on the web interface or the terminal, no refresh of the web interface is triggerd which would update the displayed information. This would be very useful for the status of a docker container when starting or stoping it.

At the moment I always have to manually refresh the page after triggering an action to see any updates in the entity file. And since a refresh removes the name of the fieldset from the URL (the URL goes from `http://olivetin/#Docker` to `http://olivetin/#`), I then have to navigate to the fieldset again if I refresh the page for a second time. This also does not look like expected behaviour to me.

In the docs on the [entites page](https://docs.olivetin.app/entities.html) it sounds to me that OliveTin is watching the entity files for changes and will then refresh the web interface: `Entities are just loaded fome files on disk, OliveTin will also watch these files for updates while OliveTin is running, and update entities.`

**Additional context**
When changing the config.yaml the web interface is automatically refreshed with any new or changed actions.

Is this a bug or expected behaviour?

**Comment by jamesread** [comment]
Hey, at the moment this is expected behaviour, but I've been working on this issue just this evening... because the current behaviour isn't very helpful! 

Will report back soon ☺️

**Comment by ioqy** [comment]
I tried the new version 2024.05.24 and now all the actions of the entity are gone.

After I downgraded back to 2024.05.13 the actions are displayed again.

**Comment by jamesread** [comment]
Oh no! That release last night was intented to include this feature you asked for! Sorry if it broke things! 

Could you show me a screenshot of your web developer console (including any red error messages), and if possible, a copy of your config?

**Comment by ioqy** [comment]
Yes, I saw it in the release notes and wanted to check it out. All fine. Don't worry.

There aren't any error messages in the log.

I also tried it with the default config that comes with OliveTin and it also doesn't show anything on the "My Containers" page.

<details><summary>Log</summary>

```
INFO OliveTin initializing                         commit="3904f85" date="2024-05-24T22:10:38Z" version="2024.05.24"
DEBU Value of -configdir flag                      value="."
INFO Setting log level to info
INFO OliveTin initialization complete
INFO OliveTin started                              configDir="/etc/OliveTin"
INFO Starting REST API                             address="localhost:1339"
INFO Loading entity file with YAML format          file="/etc/OliveTin/entities/servers.yaml" name="server"
ERRO ReadIn: open /etc/OliveTin/entities/servers.yaml: no such file or directory
INFO Loading entity file with JSON format          file="/etc/OliveTin/entities/containers.json" name="container"
INFO Starting single HTTP frontend                 address="0.0.0.0:1337"
INFO Startup action                                action="Update container entity file"
INFO Action finding by title                       actionTitle="Update container entity file"
INFO Action requested                              actionTitle="Update container entity file" tags="[startup]"
INFO Action parse args - Before                    actionTitle="Update container entity file" cmd="docker ps -a --format json > /etc/OliveTin/entities/containers.json"
INFO Action parse args - After                     actionTitle="Update container entity file" cmd="docker ps -a --format json > /etc/OliveTin/entities/containers.json"
INFO Action starting                               actionTitle="Update container entity file" timeout="3"
INFO Loading entity file with JSON format          file="/etc/OliveTin/entities/containers.json" name="container"
INFO Scheduling Action for cron                    action="Update container entity file" cronline="*/60 * * * *"
INFO Starting WebUI server                         address="localhost:1340"
INFO Found the webui directory                     dir="/var/www/olivetin"
INFO Installation ID                               content="5f0a91d5-6129-4587-a0b4-c2ba109222c7" from="/etc/OliveTin/installation-id.txt"
INFO Action finished                               actionTitle="Update container entity file" exit="0" stderr="" stdout="" timedOut="false"
INFO Update check complete                         NewVersion="none"

``` 

</details> 

<details><summary>Default config I tried it with</summary>

```yaml
# There is a built-in micro proxy that will host the webui and REST API all on
# one port (this is called the "Single HTTP Frontend") and means you just need
# one open port in the container/firewalls/etc.
#
# Listen on all addresses available, port 1337
listenAddressSingleHTTPFrontend: 0.0.0.0:1337


# Choose from INFO (default), WARN and DEBUG
logLevel: "INFO"

# Actions are commands that are executed by OliveTin, and normally show up as
# buttons on the WebUI.
#
# Docs: https://docs.olivetin.app/create-your-first-action.html
actions:
  # This is the most simple action, it just runs the command and flashes the
  # button to indicate status.
  #
  # If you are running OliveTin in a container remember to pass through the
  # docker socket! https://docs.olivetin.app/action-container-control.html
  - title: Ping the Internet
    shell: ping -c 1 1.1.1.1
    icon: ping

  # This uses `popupOnStart: execution-dialog-stdout-only` to simply show just
  # the command output.
  - title: Check disk space
    icon: disk
    shell: df -h /media
    popupOnStart: execution-dialog-stdout-only

  # This uses `popupOnStart: execution-dialog` to show a dialog with more
  # information about the command that was run.
  - title: check dmesg logs
    shell: dmesg | tail
    icon: logs
    popupOnStart: execution-dialog

  # This uses `popupOnStart: execution-button` to display a mini button that
  # links to the logs.
  - title: date
    shell: date
    timeout: 6
    icon: clock
    popupOnStart: execution-button

  # You are not limited to operating system commands, and of course you can run
  # your own scripts. Here `maxConcurrent` stops the script running multiple
  # times in parallel. There is also a timeout that will kill the command if it
  # runs for too long.
  - title: Run backup script
    shell: /opt/backupScript.sh
    shellAfterCompleted: "apprise -t 'Notification: Backup script completed' -b 'The backup script completed with code {{ exitCode}}. The log is: \n {{ stdout }} '"
    maxConcurrent: 1
    timeout: 10
    icon: backup
    popupOnStart: execution-dialog

  # When you want to prompt users for input, that is when you should use
  # `arguments` - this presents a popup dialog and asks for argument values.
  #
  # Docs: https://docs.olivetin.app/action-ping.html
  - title: Ping host
    shell: ping {{ host }} -c {{ count }}
    icon: ping
    timeout: 100
    arguments:
      - name: host
        title: host
        type: ascii_identifier
        default: example.com
        description: The host that you want to ping

      - name: count
        title: Count
        type: int
        default: 1
        description: How many times to do you want to ping?

  # OliveTin can control containers - docker is just a command line app.
  #
  # However, if you are running in a container you will need to do some setup,
  # see the docs below.
  #
  # Docs: https://docs.olivetin.app/action-container-control.html
  - title: Restart Docker Container
    icon: restart
    shell: docker restart {{ container }}
    arguments:
      - name: container
        title: Container name
        choices:
          - value: plex
          - value: traefik
          - value: grafana

  # There is a special `confirmation` argument to help against accidental clicks
  # on "dangerous" actions.
  #
  # Docs: https://docs.olivetin.app/confirmation.html
  - title: Delete old backups
    icon: ashtonished
    shell: rm -rf /opt/oldBackups/
    arguments:
      - type: confirmation
        title: Are you sure?!


  # Sometimes you want to run actions on other servers - don't overcomplicate
  # it, just use SSH!
  #
  # Docs: https://docs.olivetin.app/action-ssh.html
  # Docs: https://docs.olivetin.app/action-service.html
  - title: Restart httpd on server1
    id: restart_httpd
    icon: restart
    timeout: 1
    shell: ssh root@server1 'service httpd restart'

  # Lots of people use OliveTin to build web interfaces for their electronics
  # projects. It's best to install OliveTin as a native package (eg, .deb), and
  # then you can use either a python script or the `gpio` command.
  - title: Toggle GPIO light
    shell: gpioset gpiochip1 9=1
    icon: light

  # There are several built-in shortcuts for the `icon` option, but you
  # can also just specify any HTML, this includes any unicode character,
  # or a <img = "..." /> link to a custom icon.
  #
  # Docs: https://docs.olivetin.app/icons.html
  #
  # Lots of people use OliveTin to easily execute ansible-playbooks. You
  # probably want a much longer timeout as well (so that ansible completes).
  #
  # Docs: https://docs.olivetin.app/ansible-playbook.html
  - title: "Run Automation Playbook"
    icon: '&#129302;'
    shell: ansible-playbook -i /etc/hosts /root/myRepo/myPlaybook.yaml
    timeout: 120

  # The following actions are "dummy" actions, used in a Dashboard. As long as
  # you have these referenced in a dashboard, they will not who up in the
  # `actions` view.
  - title: Ping hypervisor1
    shell: echo "hypervisor1 online"

  - title: Ping hypervisor2
    shell: echo "hypervisor2 online"

  - title: "{{ server.name }} Wake on Lan"
    shell: echo "Sending Wake on LAN to {{ server.hostname }}"
    entity: server

  - title: "{{ server.name }} Power Off"
    shell: "echo 'Power Off Server: {{ server.hostname }}'"
    entity: server

  - title: Ping All Servers
    shell: "echo 'Ping all servers'"
    icon: ping

  - title: Start {{ container.Names }}
    icon: box
    shell: docker start {{ container.Names }}
    entity: container
    trigger: Update container entity file

  - title: Stop {{ container.Names }}
    icon: box
    shell: docker stop {{ container.Names }}
    entity: container
    trigger: Update container entity file

  # Lastly, you can hide actions from the web UI, this is useful for creating
  # background helpers that execute only on startup or a cron, for updating
  # entity files.

  - title: Update container entity file
    shell: 'docker ps -a --format json > /etc/OliveTin/entities/containers.json'
    hidden: true
    execOnStartup: true
    execOnCron: '*/60 * * * *'

# An entity is something that exists - a "thing", like a VM, or a Container
# is an entity. OliveTin allows you to then dynamically generate actions based
# around these entities.
#
# This is really useful if you want to generate wake on lan or poweroff actions
# for `server` entities, for example.
#
# A very popular use case that entities were designed for was for `container`
# entities - in a similar way you could generate `start`, `stop`, and `restart`
# container actions.
#
# Entities are just loaded fome files on disk, OliveTin will also watch these
# files for updates while OliveTin is running, and update entities.
#
# Entities can have properties defined in those files, and those can be used
# in your configuration as variables. For example; `container.status`,
# or `vm.hostname`.
#
# Docs: http://docs.olivetin.app/entities.html
entities:
  # YAML files are the default expected format, so you can use .yml or .yaml,
  # or even .txt, as long as the file contains valid a valid yaml LIST, then it
  # will load properly.
  #
  # Docs: https://docs.olivetin.app/entities.html
  - file: entities/servers.yaml
    name: server

  - file: entities/containers.json
    name: container

# Dashboards are a way of taking actions from the default "actions" view, and
# organizing them into groups - either into folders, or fieldsets.
#
# The only way to properly use entities, are to use them with a `fieldset` on
# a dashboard.
dashboards:
  # Top level items are dashboards.
  - title: My Servers
    contents:
      # The contents of a dashboard will try to look for an action with a
      # matching title IF the `contents: ` property is empty.
      - title: Ping All Servers

      # If you create an item with some "contents:", OliveTin will show that as
      # directory.
      - title: Hypervisors
        contents:
          - title: Ping hypervisor1
          - title: Ping hypervisor2

      # If you specify `type: fieldset` and some `contents`, it will show your
      # actions grouped together without a folder.
      - type: fieldset
        entity: server
        title: 'Server: {{ server.hostname }}'
        contents:
          # By default OliveTin will look for an action with a matching title
          # and put it on the dashboard.
          #
          # Fieldsets  also support `type: display`, which can display arbitary
          # text. This is useful for displaying things like a container's state.
          - type: display
            title: |
              Hostname: <strong>{{ server.name }}</strong>
              IP Address: <strong>{{ server.ip }}</strong>

          # These are the actions (defined above) that we want on the dashboard.
          - title: '{{ server.name }} Wake on Lan'
          - title: '{{ server.name }} Power Off'

  # This is the second dashboard.
  - title: My Containers
    contents:
      - title: 'Container {{ container.Names }} ({{ container.Image }})'
        entity: container
        type: fieldset
        contents:
          - type: display
            title: |
              {{ container.RunningFor }} <br /><br /><strong>{{ container.State }}</strong>

          - title: 'Start {{ container.Names }}'
          - title: 'Stop {{ container.Names }}'
``` 

</details>
