### ISSUE TITLE
Error Websocket With Nginx Proxy Manager

### ISSUE THREAD

**Issue by TheHackdes** [OliveTin/OliveTin#334]
**Here's my problem:**

I'm trying to launch the OliveTin docker image but I have a Websocket problem. I could see that in another issue the problem could be solved by commenting the first line of the config.yaml.

I personally use **Nginx Proxy Manager**. Websocket support is enabled. The web page is displayed, and the container logs show no errors.

## Version

- Docker Image OliveTin : `2024.06.04`

## **My config.yaml**

It's the same as the one generated by the docker image.
I've also tried commenting the 1st line as seen in a previous issue but it doesn't change anything.

## My Nginx Proxy Manager configuration.

|![image](https://github.com/OliveTin/OliveTin/assets/92146054/5a6dede6-fe52-4b74-a481-ffb99b065313)|![image](https://github.com/OliveTin/OliveTin/assets/92146054/6f3229e8-25d3-4268-87dd-c6d142309a78)|
|:---:|:---:|
|Details|SSL|
### WebDeveloper console logs

Below are the console logs (infinite loop) :

![image](https://github.com/OliveTin/OliveTin/assets/92146054/854878bf-e30b-4a18-a045-c4d98f28ef34)

### Docker Compose

If below my docker-compose :

```yaml
version: '3.5'
services:
  olivetin_app:
    image: 'jamesread/olivetin:latest'
    hostname: olivetin_app
    container_name: olivetin_app
    restart: always
    user: root
    volumes:
      - volume_olivetin_app_config:/config
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      network_nginx:
        ipv4_address: ${OLIVETIN_IP_NGINX}
        aliases:
          - olivetin_app
      network_olivetin:
        ipv4_address: ${OLIVETIN_IP_APP}
        aliases:
          - olivetin_app

volumes:
  volume_olivetin_app_config:
    name: volume_olivetin_app_config
    external: false
networks:
  network_olivetin:
    name: network_olivetin
    ipam:
     config:
       - subnet: ${OLIVETIN_IP_SUBNET}
  network_nginx:
    external:
      name: network_nginx
```

### Docker Logs

Below are the logs of my docker container:

```text
# docker logs -f olivetin_app
level="info" msg="OliveTin initializing" commit="362a97c" date="2024-06-04T12:21:11Z" version="2024.06.04"
level="debug" msg="Value of -configdir flag" value="."
level="info" msg="Setting log level to info"
level="info" msg="OliveTin initialization complete"
level="info" msg="OliveTin started" configDir="/config"
level="info" msg="Starting REST API" address="localhost:1339"
level="info" msg="Loading entity file with YAML format" file="/config/entities/servers.yaml" name="server"
level="info" msg="Starting WebUI server" address="localhost:1340"
level="info" msg="Found the webui directory" dir="/var/www/olivetin"
level="info" msg="Starting single HTTP frontend" address="0.0.0.0:1337"
level="info" msg="Loading entity file with JSON format" file="/config/entities/containers.json" name="container"
level="info" msg="Update check remote version: &{ApiVersion:2 Latest:2024.06.04 History:map[2021-11-06:security]}"
level="info" msg="Update check complete" CurrentVersion="2024.06.04" NewVersion="none"
```

Do you have any idea where my problem might be?

Thank you for your help. I hope the information given is sufficient :)
