### ISSUE TITLE
Wrong entity is used in dropdown when original entity file is overwritten

### ISSUE THREAD

**Issue by XLixl4snSU** [OliveTin/OliveTin#337]
Setup:
Alpine Linux Docker Container, OliveTin installed as shown here: https://docs.olivetin.app/install-alpine.html

I have two entities:

```
entities:
  - file: /etc/OliveTin/backup_list.json
    name: backuplist
    
  - file: /etc/OliveTin/logfile_list.json
    name: logfilelist
```
and the following action:
```
actions:
  - title: Show logs
    shell: 'cat /config/logs/{{ logtype }}-{{ logfiledate }}.log'
    icon: "&#128203;"
    popupOnStart: execution-dialog-stdout-only
    arguments:
      - name: logfiledate
        entity: logfilelist
        title: 'Select Date'
        choices:
          - value: '{{ logfilelist.date }}'
            title: '{{ logfilelist.readableDate }}'
      - name: logtype
        title: 'Select type of log'
        choices:
          - title: backup script log
            value: backup_script
          - title: rsync log
            value: rsync
```

When I start up the container and the entity json files are created for the first time everything works as expected, but as soon as the file for entity "logfilelist" is deleted and/or replaced with an updated version, my actions dropdown menu shows the entries of a completely different entity, in this case the "backuplist" entity. I have to restart OliveTin for it to work normally again.

Before making changes to the json file:
![image](https://github.com/OliveTin/OliveTin/assets/111450124/0f7e63ce-65d8-4c40-99e4-7d548200ee87)

After making changes to the json file (only the entry for "26.06.2024" is removed in the "logfile_list.json", this data now comes from the "backup_list.json" file): 
![image](https://github.com/OliveTin/OliveTin/assets/111450124/d0a97b85-8aa9-4a7f-9822-62596a58c924)

The file is created the following way in bash (outputting a json formatted line per array entry):

`printf "%s\n" "${json_logfile_list[@]}" > /etc/OliveTin/logfile_list.json`

The issue does not occur if I manually edit the file in place. I suspect the issue is how replaced files are handled.

Switching the entities around in config like this:
```
entities:

  - file: /etc/OliveTin/logfile_list.json
    name: logfilelist

  - file: /etc/OliveTin/backup_list.json
    name: backuplist
```
results in entity "logfilelist" not being updated at all until OliveTin is restarted.

Logs are only showing changes to entity "backuplist", even though "logfilelist" definitely also changes.

> INFO fsnotify event &{callbackWrapper:0xc00025b6d0 callbackComplete:false}
INFO Loading entity file with JSON format          file="/etc/OliveTin/backup_list.json" name="backuplist"
