### ISSUE TITLE
Add a "time until the next execution available" indicator

### ISSUE THREAD

**Issue by sirjmann92** [OliveTin/OliveTin#338]
I love OliveTin, it helps me accomplish several things and I run multiple instances across different servers (both Windows and Linux). I have several tasks that run for several seconds/minutes after the launch script completes successfully in OliveTin. OliveTin reports the job has completed successfully because the job is simply to execute another job/script that kicks off a process that takes time to execute. Since the actual process was kicked off by an intermediary job that was triggered by OliveTin, this means OliveTin isn't aware of any success/failure of the actual job. This also means the OliveTin UI is opened and available during the execution of the actual job, so a user can repeatedly launch the same job, or other jobs, while it's executing which can obviously cause issues.

I'd like to be able to create an artificial timer in the OliveTIn config that isn't tied to the success/failure of the actual task but locks the UI into the confirmation dialog for a configurable duration, before reporting success/failure, so that I can ensure users aren't able to relaunch the same job, or other jobs, during the execution of the intended task. If locking the UI behind the confirmation dialog is too large of a request requiring too many changes, I'd still be interested in displaying the timer/countdown before reporting success/failure, and as an MVP just waiting for the given time until reporting success/failure would suffice, although seeing how long is remaining would be very nice to have.

Apologies if I made it sound confusing, it makes sense in my head... lol

I've tried using "timeout /t 150 /nobreak" in my batch scripts but OliveTin balks that input redirection is not supported (even though I disabled input for the timeout with "/nobreak", I suspect because you can still break out of a timeout with CTRL-C, which is an input). So... if OliveTin can't "redirect input" for batch timeouts, a native timer would be very helpful (NOT the same as the timeout, which doesn't create the desired behavior for this use-case). I've also tried adding the timeout string directly in OliveTin but the result is the same ("input redirection is not supported"). And the "sleep" option isn't available in Windows.

If this is already possible and I've missed a feature, please point it out. I couldn't find it in the documentation.

**Comment by jamesread** [comment]
Hey @sirjmann92 , thanks for taking time to write that up, it certainly makes sense. 

I think what you're asking for is rate limiting, whicjtos documented here: https://docs.olivetin.app/ratelimits.html

So for example, you could do: 


```yaml
actions:
  - title: run big script
    shell: ...
    maxRate: 
      - limit: 1
        duration: 1h
```

To only allow the script once per hour?

**Comment by sirjmann92** [comment]
Oh interesting! Thanks @jamesread , that will definitely do the trick to keep someone from executing the same job! However, sometimes the user is dependent on the completion of the job so they can execute another task. This solution wouldn't help in that case, you would just know that you can't execute the same job again within a given timeframe, but only if you attempt to execute the job. As an enhancement, and for a better user experience, if there's a message or timer that could be displayed in the UI so that a user knows when the job has completed (timer has expired) so they can execute another task that was dependent on the completion of the previous task, this would be ideal!

Thanks again! I'll definitely use this in the interim, and hope for an enhancement in the future!

**Comment by sirjmann92** [comment]
I'm not having any success with rate limiting.

```
actions: 
  - title: Stop Soulmask
    shell: save-exit_soulmask.bat
    maxConcurrent: 1
    timeout: 10
    maxRate:
      - limit: 1
        duration: 3m
    icon: '<img src="customIcons/Soulmask.ico" width="48px"/>'
    popupOnStart: execution-dialog
    arguments:
      - type: confirmation
        title: This will take three (3) minutes... Save world and shutdown server?
```
Results in:
`Blocked from executing. This action has run 0 out of 0 allowed times in the last 3m.`
