### ISSUE TITLE
Generate arguments from a loop

### ISSUE THREAD

**Issue by crnakad** [OliveTin/OliveTin#37]
Is it possible to integrate a jinja2 like structure, where we can use a for loop to generate the arguments of an action?

**Comment by jamesread** [comment]
Hey @crnakad , really interesting idea, and not something I have thought of before. I know Jinja2 well.

Could you give an example of where  you think this would be useful, though?

**Comment by crnakad** [comment]
What I'm trying to do is give the users a way to stop, start, or restart docker containers on multiple machines through this interface.

The user selects a machine as an argument choice, and based on the value selected, the following argument displays all the running containers on this machine as choices.

I don't want to add the container names manually in the config file, so I want a way to dynamically generate the possible choices based on a previous argument value.

Thank you!

**Comment by Markus-** [comment]
So you want to combine multiple actions as you need to start the action "get information for <arg1>" and use this return value (in which format btw?) for the loop structure for the next action.

I am also thinking about it while creating kind of specific customer template and I probably will start with multiple instances (one per customer) and prefilled config files.

**Comment by matthewstrasiotto** [comment]
As discussed in [discord](https://discord.com/channels/846737624960860180/846737624960860183/962097384052129843):



For this sort of thing, you'd probably want to allow an alternative spec for dropdowns, where users call a command that generates a list, maybe newline separated or something. You'd have to leave implementing the list generator in user's hands, but for docker it might look like this:

```yaml
arguments:
 - name: Container
   choice_generator: "docker ps --format '{{ .Names }}'"
```

With additional options for refresh interval (seconds, probably) and timeout (seconds also, probably)

```yaml
arguments:
 - name: Container
   choice_generator: 
      command: "docker ps --format '{{ .Names }}'"
      refresh_interval: 60
      timeout: 15
```

**Comment by samcro1967** [comment]
I too would like for a way to dynamically generate lists for argument values.  Would also not be opposed to having it point to a file and I generate the list outside of OliveTin with cron if that is easier to implement.  I am also finding that I am often using the same list for multiple actions.  Would also be a plus if the list could be made "global" in nature and just referenced as needed in the appropriate actions.  This way if it is generated inside of OliveTin it is only ran once and not for each action it is being used by.

**Comment by samcro1967** [comment]
I created the docker_ps.sh script below to update config.yaml with the list of running containers:

```
#!/bin/bash
cd /home/user/Documents/Docker/olivetin
docker ps --format '{{ .Names }}' | sort| awk '{print "        - value: ", $1}' > containers.txt
chown 1000:1000 containers.txt
chmod 777 containers.txt

sed -i -e '
  /^#StartDocker/,/^#EndDocker/!b
  //!d;/^#EndDocker/!b
  r containers.txt
  N
' config.yaml
```

My config.yaml looks like this for managing my docker containers from OliveTin:
```
- title: Docker Container Management
  icon: '<img src = "https://www.docker.com/wp-content/uploads/2022/03/Moby-logo.png" width = "48px"/>'
  shell: docker {{ command }} {{ container }}
  timeout: 120
  arguments:
    - name: command
      title: Command
      choices:
        - value: rm -f
        - value: restart
        - value: start
        - value: stop
    - name: container
      title: Container
      choices:
#StartDocker
        - value:  service1
        - value:  service2
        - value:  service3
        - ...
#EndDocker
```
I setup docker_ps.sh as an action in OliveTin to run the script to update the list of running containers in config.yaml:
```
- title: OliveTin Update Docker Containers
  icon: '<img src = "customIcons/OliveTinLogo.png" width = "48px"/>'
  shell: /home/user/Documents/Docker/olivetin/docker_ps.sh
  timeout: 60
```
I then have another action in OliveTin to restart the OliveTin service:
```
- title: Restart Service
  icon: '<img src = "customIcons/restart.jpg" width = "48px"/>'
  shell: sudo systemctl restart {{ service }}
  timeout: 60
  arguments:
    - name: service
      title: Service
      choices:
        - value: OliveTin
        - value: smbd
```

To do an update from the OliveTin GUI
```

1. Run OliveTin Update Docker Containers (docker_ps.sh)
2. Run Restart Service and restart the locally installed OliveTin service from the OliveTin GUI
3. Do a browser refresh
4. Now the list of containers in the Docker Container Management action is updated.
```
