### ISSUE TITLE
List inside an entity for dropdown

### ISSUE THREAD

**Issue by r3nor** [OliveTin/OliveTin#411]
First of all, thank you for building such an amazing tool. 

I currently ran into a limitation: I have a list of entities that look like this:

```
{"Name":"caddy","Status":"running(1)","ConfigFiles":"/home/whoami/caddy/docker-compose.yml","containers":["caddy"]}
```

I am trying to build an action that, for a certain `docker compose` project, it lets the user interact with the containers individually. Say restart them, see the logs, etc. For this, I need to acceess the `entity.Containers[]` list, and use it as the iterated value for the dropdown selection... I am not sure how should I do that...

I have this idea, which obiously does not work:

```
  - title: '{{ dockercompose.Name }} shell'
    shell: docker restart {{containerToRestart}}
    entity: dockercompose
    arguments:
      - name: containerToRestart
        entity: dockercompose.Containers
        title: 'Select Container'
        choices:
          - value: '{{ . }}'
            title: '{{ . }}'
```

Any help with this? 

Here's the script I use to get the entity JSON, it basically returns `docker compose ls --json` combined with the container list for each compose so I can easily access them:

```
#!/bin/bash

compose_json=$(docker compose ls -a --format json)
final_compose="["

while read -r compose; do
    name=$(echo "$compose" | jq -r '.Name')
    containers=$(docker compose -p "$name" ps --format '{{.Name}}' | jq -R . | jq -s .)
    if [ -z "$containers" ] || [ "$containers" == "null" ] || [ "$containers" == "[]" ]; then
        containers="[]"
    fi

    compose_with_containers=$(echo "$compose" | jq --argjson cont "$containers" '. + {containers: $cont}')
    final_compose+="$compose_with_containers,"
done < <(echo "$compose_json" | jq -c '.[]')

final_compose="${final_compose%,}]"
echo "$final_compose" | jq -c '.[]'
```

With this, I am able to run actions such as this one, that shows a docker compose project logs:

```
  - title: Logs {{ dockercompose.Name }} stack
    icon: <iconify-icon icon="octicon:log-24"></iconify-icon>
    shell: docker compose -p {{dockercompose.Name}} logs -n 100 -f
    entity: dockercompose
    popupOnStart: execution-dialog
    timeout: 360
```
