### ISSUE TITLE
Allow interaction with the standard input

### ISSUE THREAD

**Issue by vganin** [OliveTin/OliveTin#418]
**Is your feature request related to a problem? Please describe.**
This is closely related to https://github.com/OliveTin/OliveTin/issues/22, although I wanted to raise a feature request to allow interaction with the standard input yet again. My use case is to run [beets.io](https://beets.io/) music organiser by clicking the action with a dialog. Example:
```yaml
actions:
  - title: "Import music with Beets"
    shell: beet import "{{ From }}"
    popupOnStart: execution-dialog
    icon: <iconify-icon icon="game-icons:beet"></iconify-icon>
    arguments:
      - name: From
        choices:
          - title: Downloads
            value: /downloads
          - title: Existing library
            value: /music
```

Briefly, what `beet import` does is it consumes the folder containing the music, sorts it and finally puts it into the pre-defined location set in its own config. It runs mostly automatic, but in difficult cases it [might ask the user for assistance, essentially specify key decisions with one letter commands](https://beets.readthedocs.io/en/stable/guides/tagger.html#choices), so there is no way to pre-define that with arguments or other kind of configuration.

**Describe the solution you'd like**
- Add an input text field to interact with the standard input of the running program in the dialog
- Ideally, notify the user that action requires input

**Describe alternatives you've considered**
There is a beets-dedicated program https://github.com/sentriz/betanin that already does that (having web GUI with console prompt to control beets as it runs), but it's confined to beets usage and have other features that I don't need, so I consider it as overkill for my case. It's also not that well supported compared to OliveTin. OliveTin seems generic and simple enough to build my entire self-hosted empire control centre :D

**Additional context**
Beets can run in a quiet mode `beet import -q`, thus silently skip all "difficult" cases mentioned above. But in this workflow I have to log in to my server to run it manually with the input to assess only difficult cases, which is inconvenient. But that's what I'm doing at the moment.
