### ISSUE TITLE
How to avoid using "very_dangerous_raw_string" with a URL

### ISSUE THREAD

**Issue by aristosv** [OliveTin/OliveTin#42]
**What seems to be the problem?!**
I am currently using OliveTin on a Raspberry Pi that I'm building as a digital signage system. So basically OliveTin is used to run various bash scripts that display images, websites, or play audio and video on the screen the Raspberry Pi is connected.

I would like to avoid using the type "very_dangerous_raw_string", but I think some of the characters in the URL are not allowed. I tried "ascii_identifier" and "ascii_sentence" but this was the only way I could get it to work.

**Your config.yaml**
```
- title: Play YouTube
  shell: echo {{ youtube }} | /home/pi/digitalsignage/signage_youtube_stream
  arguments:
    - name: youtube
      title: YouTube Link
      type: very_dangerous_raw_string
      default: https://youtu.be/QC8iQqtG0hg
```

**What package/file/container did you use to install OliveTin?**
OliveTin_2022-01-06_linux_arm64.deb

**Comment by jamesread** [comment]
Hey @aristosv , thanks for reporting this issue. This is certainly something that makes sense - a "url" datatype. 

I did have a little play around with the source code for this, but the regex for a valid URL is pretty complex. 

I'll do some more fiddling around and try to get this added to the next release.

**Comment by vladosam** [comment]
Hello @jamesread, can i use at sign "@" in arguments without using  very_dangerous_raw_string?

**Comment by soar** [comment]
It would be great to have an option to set a regex for string validation, like:
```yaml
        arguments:
          - name: message
            type: regex
            regex: [a-z0-9:/.-]+
```
