### ISSUE TITLE
Add support for config file splitting and inclusion

### ISSUE THREAD

**Issue by hialvaro** [OliveTin/OliveTin#428]
First of all, thank you for building OliveTin, it's a very useful and nice tool.

As I am expanding the actions on my OliveTin, the config file is getting bigger and bigger. I would love to be able to split up the config file in smaller ones and include them as I wanted. I imagine something simple, such as being able to put `include: /path/to/another.yml` and the content being inserted there.

For example, I want to have actions that are for a certain provider, say aws. I could have a `actions/aws.yml` file with all the actions. Same with dashboards... Then in olivetin config yml file we could have a much cleaner config:

```yml
actions:
    include: actions/aws.yml
    include: actions/azure.yml
    include: actions/entity_generators.yml

    - title: Ping a Server
      shell: ping -c 3 1.1.1.1
      icon: ping
      popupOnStart: execution-dialog-stdout-only

dashboards:
    include: dashboards/my_dashboard.yml
    include: dashboards/aws_dashboard.yml
```
