### ISSUE TITLE
Entity from command

### ISSUE THREAD

**Issue by hialvaro** [OliveTin/OliveTin#436]
As a user, I sometimes would like to get an entity directly from a command instead of a local file. 

For example:

```yml
actions:
    - title: RESTART {{ servers.Name }}
    timeout: 30
    acls: ["admin"]
    shell: 'bash /scripts/restart_server.sh {{eb_envs.EnvironmentId}}'
    entity: servers

entities:
    - command: 'curl -X GET https://some-api/servers'
      name: servers
    - file: entities/other.yml
      name: other
```

This way, a cron can be avoided and the entity is requested on-demand, always updated. I imagine that the entity command is executed as soon as the action is invoked, then the output of that command is used as the entity itself.

**Comment by jamesread** [comment]
You could just redirect the output of the curl to a local file? 

```yaml
actions: 
  - title: Get entities
    shell: curl -X GET https://some-api/servers > /etc/OliveTin/entities/remote.yaml'
    execOnStartup: true
```
