### ISSUE TITLE
Special users do not have default ACL permissions

### ISSUE THREAD

**Issue by hialvaro** [OliveTin/OliveTin#442]
If i set the default permissions like:

```yml
defaultPermissions:
  view: true
  exec: false
  logs: false
```

and create some ACLs:

```yml
accessControlLists:
  - name: admins
    addToEveryAction: true
    matchUsernames:
      - someone
    permissions:
      view: true
      exec: true
      logs: true

  - name: "developer"
    addToEveryAction: false
    matchUsernames:
      - developer
    permissions:
      view: true
      exec: true
      logs: false
```

The `startup` and `cron` users do not have permissions to execute, hence their automated actions are blocked. However, if I add them to the "admins" ACL like:

```yml
accessControlLists:
  - name: admins
    addToEveryAction: true
    matchUsernames:
      - someone
      - startup # <---added
      - cron # <---added
    permissions:
      view: true
      exec: true
      logs: true
```

Then the automated actions can be run without problems. I would assume that the special users should have separate permissions. In the end if an entity needs automated updates it should be updated regardless of the logged in user, right? Maybe I'm wrong and there's a better reasoning for this behavior.
