### ISSUE TITLE
ACLS attribute for the dashboards

### ISSUE THREAD

**Issue by alanmilinovic** [OliveTin/OliveTin#445]
Please add that dashboards support acls attribute, so that we can prevent unauthorised users from accessing certain dashboards.

If user has no rights on particular dashboard also please automatically hide it from the side menu.

**Comment by hialvaro** [comment]
I am also interested in being able to set ACLs for dashboards

**Comment by jamesread** [comment]
This sounds reasonable. 

However, note that you can now set `authRequireGuestsToLogin: true` to at least hide the dashboards from guests.

**Comment by alanmilinovic** [comment]
> This sounds reasonable.
> 
> However, note that you can now set `authRequireGuestsToLogin: true` to at least hide the dashboards from guests.

That is nice feature, but I want to keep guest having no need for login. Please also check this issue https://github.com/OliveTin/OliveTin/issues/449.

**Comment by jamesread** [comment]
Hey @alanmilinovic Please check release 2025.6.6 for this fix, and let me know if it works for you :-)

**Comment by alanmilinovic** [comment]
Not working as intended. All my actions are now under Actions in the menus although I have actions under dashboards.

**Comment by jamesread** [comment]
Hey, it looks like I introduced an unintended bug. I'll patch this tonight.

**Comment by alanmilinovic** [comment]
Any update on this one?

**Comment by alanmilinovic** [comment]
Any update dear @jamesread?

**Comment by jamesread** [comment]
Hey @alanmilinovic , do we think this issue is historical now?

**Comment by alanmilinovic** [comment]
> Hey [@alanmilinovic](https://github.com/alanmilinovic) , do we think this issue is historical now?

Well, the bug with actions is fixed, but the feature itself is still not there. I cannot use acls on the dashboards itself to hide a complete dashboard from the guest user.

**Comment by jamesread** [comment]
Hey @alanmilinovic . If none of the actions on a dashboard can be viewed by the guest user (or anyone else), it should be hidden automatically now. 

On reflection, I want ACLs to only apply to auctions, and Dashboards should be hidden / shown automatically. 

Let me know if your guest user sees dashboards with 0 actions. If so, please can you share your config.

**Comment by alanmilinovic** [comment]
`````
  - title: Services
    contents:
      - title: '{{ systemd_unit.description }}'
        type: fieldset
        entity: systemd_unit
        contents:
          - title: 'Status: {{ systemd_unit.sub }}'
            cssClass: '{{ systemd_unit.sub }}'
            type: display

          - title: Start {{ systemd_unit.unit }}
          - title: Stop {{ systemd_unit.unit }}
          - title: Status {{ systemd_unit.unit }}
          - title: Restart {{ systemd_unit.unit }}
`````

```
  - title: Start apache2.service
    icon: <iconify-icon icon="ic:round-directions-run"></iconify-icon>
    shell: removed command'
    hidden: true
    entity: systemd_unit
    triggers: Update services file
    acls:
      - admins
```

`{"unit":"apache2.service","load":"loaded","active":"active","sub":"running","description":"The Apache HTTP Server"}`

So I can still see the dashboard with the guest. To be honest I do not like this automatic logic, would be nice to have more control and hide the dashboard independently.
