### ISSUE TITLE
show text-box only when specific option is selected from dropdown

### ISSUE THREAD

**Issue by aristosv** [OliveTin/OliveTin#45]
**What seems to be the problem?!**
I am giving the option to play a local video, or stream a video from a URL. Is there a way to make the text-box appear only when the stream option is selected from the dropdown menu?

**What package/file/container did you use to install OliveTin?**
OliveTin_2022-01-06_linux_arm64.deb

**Your config.yaml**
```
- title: Play Video
  icon: "&#128250"
  shell: echo {{ videolink }} | {{ localorstream }}
  arguments:

   - name: videolink
     title: Video Link
     type: very_dangerous_raw_string
     default: $videourl

   - name: localorstream
     title: Local or Stream
     choices:
      - title: Local
        value: $workingdir/signage_video_local

      - title: Stream
        value: $workingdir/signage_video_stream
```

**Screenshot**
![Greenshot 2022-02-13 17 26 48](https://user-images.githubusercontent.com/528302/153760292-4ade7538-4bc0-4d8f-b058-7dc5d5adfa10.png)
