### ISSUE TITLE
Subfolders should inheirit entities

### ISSUE THREAD

**Issue by alanmilinovic** [OliveTin/OliveTin#450]
Please consider supporting nested display inside folder.

This is an example, currently this configuration is not working:
```
dashboards:
  - title: Dashboard
    contents:
      - title: Test title (first fieldset)
        type: fieldset
        contents:
          - title: Test title 2 (folder)
            contents:
              - title: action1
              - title:  Test title 3 (second fieldset)
                entity: entity1
                type: fieldset
                contents:
                  - type: display
                    title: |
                      {{ custom.dispaly_content }}
```
Result is that "display" element is not there. If I move it outside of the folder it is shown.
