### ISSUE TITLE
Password Hashing Actions

### ISSUE THREAD

**Issue by Josh-su** [OliveTin/OliveTin#470]
Hi, I'm trying to add an action to hash passwords more easily, but I encountered some problems:

#### For the "Hash Password Package" action
It works, but I need to find a way to reinstall the packages each time I update or restart the container in Unraid.

#### For the "Hash Password API" action
The API works in the terminal, but not in the "shell:" command because it contains a ":" in the command, which is interpreted as an attempt to add a new mapping value.
![image](https://github.com/user-attachments/assets/07ab025e-3fca-4c32-acb3-813bd73c788b)
#### Logs Message:
```
level="error" msg="Config file error at startup. While parsing config: yaml: line 22: mapping values are not allowed in this context"
```
#### Actions
```
  - title: Hash Password Package
    icon: <iconify-icon icon="mynaui:hash-square"></iconify-icon>
    popupOnStart: execution-dialog-stdout-only
    shell: echo -n "{{ Password }}" | argon2 "$(openssl rand -base64 16)" -id -t 4 -m 16 -p 6 -l 32 -e
    arguments:
      - name: Password
        # description: "Password must be 8-16 characters long, include at least one uppercase letter, one lowercase letter, one number, one special character, and contain no spaces."
        # type: 'regex:^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[^\w\s])\S{8,16}$'
        
  - title: Hash Password API
    icon: <iconify-icon icon="mynaui:hash-square"></iconify-icon>
    popupOnStart: execution-dialog-stdout-only
    shell: curl -sS --json '{"password": "{{ Password }}"}' http://olivetin.example.com:1337/api/PasswordHash
    arguments:
      - name: Password
```
