### ISSUE TITLE
Error when authenticating with OAuth2 (Authentik)

### ISSUE THREAD

**Issue by ad3m3r5** [OliveTin/OliveTin#474]
**What seems to be the problem?!**

I have Authentik setup with many different applications, so I know that it works with oauth2, oidc, and ldap.

With most containers, I had to pass my certificate bundle from the host to the container to allow it to use my internal CA.
I verified this works by using curl in the running OliveTin container before and after it was added.

After clicking "Login with Authentik", I am redirected to the Authentik webpage successfully.
When Authentik then redirects back to OliveTin: `https://olivetin.mydomain.com/oauth/callback?code=xxxxxxxxxxxxxxxxxxxxxxxxx`
The webpage goes black with white text: `Failed to exchange code`

**Can you provide a sosreport?**

```
### SOSREPORT START (copy all text to SOSREPORT END)
# Build: 
commit: 13e48dd
version: 2024.11.09
date: \"2024-11-09T23:27:09Z\"

# Runtime:
os: linux
osreleaseprettyname: PRETTY_NAME=\"Fedora Linux 40 (Container Image)\"
arch: arm64
incontainer: true
lastbrowseruseragent: \"\"
user: \"\"uid: \"\"
sshfoundkey: /config/ssh/id_rsa
sshfoundconfig: not found at /home/olivetin/.ssh/config
availableversion: none

# Config:
countofactions: 2
countofdashboards: 0
loglevel: DEBUG
listenaddresssinglehttpfrontend: 0.0.0.0:1337
listenaddresswebui: localhost:1340
listenaddressrestactions: localhost:1338
listenaddressgrpcactions: localhost:1339
timezone: Local
timenow: 2024-11-10 05:29:33.36577923 +0000 UTC m=+157.206135921
configdirectory: /config
webuidirectory: /var/www/olivetin (/var/www/olivetin/)
themesdirectory: /config/custom-webui

### SOSREPORT END  (copy all text from SOSREPORT START)
```

**What package/file/container did you use to install OliveTin?**

DockerHub - `2024.11.09` and `latest`

**Your config.yaml**

```
listenAddressSingleHTTPFrontend: 0.0.0.0:1337

logLevel: "DEBUG"

checkForUpdates: false

authOAuth2RedirectURL: "https://olivetin.mydomain.com/oauth/callback"
authOAuth2Providers:
  authentik:
    name: authentik
    title: Authentik
    clientID: "myclientid"
    clientSecret: "myclientsecret"
    authURL: "https://authentik.mydomain.com/application/o/authorize/"
    tokenURL: "https://authentik.mydomain.com/application/o/token/"
    whoamiURL: "https://authentik.mydomain.com/application/o/userinfo/"
    usernameField: "preferred_username"
    icon: <iconify-icon icon="simple-icons:authentik"></iconify-icon>
```

**OliveTin logs**

```
olivetin  | level="info" msg="OAuth2 state: xxxxxxxxx== mapped to provider authentik (found: true), now redirecting"
olivetin  | level="debug" msg="err: websocket: close 1001 (going away)"
olivetin  | level="info" msg="OAuth2 Callback received"
olivetin  | level="debug" msg="OAuth2 Token Code" state="xxxxxxxxxx==" token-code="xxxxxxxxxxxxxxxxxxxxxx"
olivetin  | level="error" msg="Failed to exchange code: Post \"https://authentik.mydomain.com/application/o/token/\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
```

**Screenshot of WebDeveloper console logs**

` GET https://olivetin.mydomain.com/oauth/callback?code=xxxxxxxxxxxxx&state=xxxxxxxxxxxx 400 (Bad Request)`

**Anything else?**

The setup is very basic and new, OAuth2 was basically the first thing I configured. I changed carious Authentik settings as well as nginx-proxy-manager (used everything recommended on both) to try and fix the issue, but nothing has worked.

As a recommendation, it might be good to allow `showNavigation` to be `false`, but still show the login. When disabling navigation, the login was hidden as well, which was quite confusing.
