### ISSUE TITLE
Member with admin role cannot view actions, this error appear "Zero actions found - check that you have some actions defined, with a view permission"

### ISSUE THREAD

**Issue by tissoni** [OliveTin/OliveTin#475]
**Describe the bug**
When trying to view actions as a user admin logged in this error appear "Zero actions found - check that you have some actions defined, with a view permission". 
**To Reproduce**

this is my config file 

```
authLocalUsers:
  enabled: true
  users:
    - username: chelo
      password: 
      groups:
        - admins

accessControlLists:
  - name: admins
    matchUsergroups:
      - admins
    permissions:
      view: true
      exec: true

  - name: chelo
    matchUserNames:
      - chelo
    permissions:
      view: true
      exec: true

authRequireGuestsToLogin: true
```

**Comment by jamesread** [comment]
Heya @tissoni , sorry that you had to raise this issue, perhaps I could make the docs a bit clearer, or better examples. What's probably happening is that the ACL isn't associated with any actions (an ACL brings together an Action, a User, and a set of Permissions).

You need to add the ACL to the actions that you want it to apply to. You can do this manually on a per-action basis, like this;

```yaml
actions:
  - title: date
    shell: date
    acls:
      - admins
```

Or, do it globally on the ACL with `addToEveryAction: true`;

```yaml

accessControlLists:
  - name: admins
    addToEveryAction: true
    matchUsergroups:
      - admins
    permissions:
      view: true
      exec: true
```

**Comment by jamesread** [comment]
Heya, 

So `authRequireGuestsToLogin: true` will mean that guests always have zero actions . If you don't want guests to execute or view, I recommend putting this back to "true". 

I've made some changes just now to improve log messages a bit here for the future.

However for now, can you set "logLevel: DEBUG", and refresh the page, and look for log messages that start "UserFromContext". Do you see anything in the "acls" log line?

**Comment by tissoni** [comment]
Sure @jamesread, here is my log file with the debug on:
```
level="info" msg="Setting log level to info"
2024/11/14 19:52:56 error reading config file: While parsing config: yaml: unmarshal errors:
  line 112: mapping key "shell" already defined at line 95
  line 113: mapping key "icon" already defined at line 96
  line 114: mapping key "timeout" already defined at line 97
  line 115: mapping key "popupOnStart" already defined at line 98
  line 116: mapping key "arguments" already defined at line 99
level="info" msg="Config file changed:WRITE         \"/config/config.yaml\""
level="info" msg="Setting log level to info"
level="warning" msg="Could not find local user session: "
level="warning" msg="Could not find local user session: "
level="warning" msg="Could not find local user session: "
level="warning" msg="Could not find local user session: "
level="warning" msg="Could not find local user session: "
level="warning" msg="Could not find local user session: "
level="info" msg="Config file changed:WRITE         \"/config/config.yaml\""
level="info" msg="Setting log level to info"
level="info" msg="Config file changed:WRITE         \"/config/config.yaml\""
level="info" msg="Setting log level to info"
level="warning" msg="Could not find local user session: "
level="warning" msg="Could not find local user session: "
level="warning" msg="Could not find local user session: "
level="warning" msg="Could not find local user session: "
```

**Comment by jamesread** [comment]
ooh, your config doesn't look good. See those errors around line 95/112? That might not be the root cause, but it certainly needs to be fixed.

It's possibly a missing "-" to start a new item in one your actions, it looks like? 

Restart OliveTin afterwards, and check that you have a clean config in the logs. 

I don't see any "UserFromContext" logs in what you pasted, but it's probably because the config is broken right now.

**Comment by tissoni** [comment]
@jamesread Thanks for your reply.

I have copied the default config file of olivetin, and start a new one with my username and password and ACLs

```
listenAddressSingleHTTPFrontend: 0.0.0.0:1337
checkForUpdates: false
pageTitle: Infrastructure Management Tool
showNavigation: true
showFooter: false
authRequireGuestsToLogin: true
logLevel: "INFO"

authLocalUsers:
  enabled: true
  users:
    - username: chelo
      password: 
      groups:
        - admins

accessControlLists:
  - name: admins
    addToEveryAction: true
    matchUsergroups:
      - admins
    permissions:
      view: true
      exec: true

actions:
  - title: Shutdown Reactor
    acls:
      - admins
```

but the problem continues, here it is my log file:

```
level="info" msg="Execution finished: datetime_started:\"2024-11-15 12:51:49\"  action_title:\"Shutdown Reactor\"  user:\"guest\"  action_icon:\"&#x1F600;\"  execution_tracking_id:\"09693c41-e9d7-4aa9-be35-6da88307c887\"  datetime_finished:\"2024-11-15 12:51:49\"  action_id:\"ed7fd756-d65a-4030-9bf7-901fd288a0cc\"  execution_started:true  execution_finished:true+v"
level="info" msg="Config file changed:WRITE         \"/config/config.yaml\""
level="info" msg="AuthRequireGuestsToLogin is enabled. All defaultPermissions will be set to false"
level="info" msg="Setting log level to info"
level="warning" msg="Could not find local user session: "
level="warning" msg="Could not find local user session: "
level="warning" msg="Zero actions found - check that you have some actions defined, with a view permission"
level="warning" msg="Zero actions found - check that you have some actions defined, with a view permission"
level="warning" msg="Zero actions found - check that you have some actions defined, with a view permission"
```
