### ISSUE TITLE
empty usergroup when authenticating with OAuth2 (Authentik)

### ISSUE THREAD

**Issue by e1ke** [OliveTin/OliveTin#477]
**What seems to be the problem?!**
I am trying to login with authentik, everything is working, besides the transfer of the user's groups to olivetin. 
I am running olivetin in a docker container on a different server than authentik. 
I followed the tutorial here
https://docs.olivetin.app/oauth2-authentik.html
but could not find any difference to my authentik setup. I tried to add a scope-mapping (see end of this post) for olivetin, where set the usergroup but I think I am doing sth wrong on that part.
In olivetin config.yml I can filter with ACL by username, but i want anyone in a specific group ("Authentik-Admins") to permit access to the olivetin instance.
I am thinking about using just a proxy outpost to secure olivetin to my Authentik-Admins but that is not the purpose of your great work with integrating authentik over OIDC.

**Can you provide a sosreport?**
sure
```
### SOSREPORT START (copy all text to SOSREPORT END)

# Build:
commit: 655a7f2
version: 2024.11.18
date: "2024-11-14T22:00:08Z"

# Runtime:
os: linux
osreleaseprettyname: PRETTY_NAME="Fedora Linux 40 (Container Image)"
arch: amd64
incontainer: true
lastbrowseruseragent: ""
user: ""
uid: ""
sshfoundkey: not found at /root/.ssh/id_rsa
sshfoundconfig: not found at /root/.ssh/config
availableversion: none

# Config:
countofactions: 4
countofdashboards: 0
loglevel: DEBUG
listenaddresssinglehttpfrontend: 0.0.0.0:1337
listenaddresswebui: localhost:1340
listenaddressrestactions: localhost:1338
listenaddressgrpcactions: localhost:1339
timezone: Local
timenow: 2024-11-20 20:53:11.924622718 +0000 UTC m=+23670.037418131
configdirectory: /config
webuidirectory: /var/www/olivetin (/var/www/olivetin/)
themesdirectory: /config/custom-webui

### SOSREPORT END  (copy all text from SOSREPORT START)
```

**What package/file/container did you use to install OliveTin?**
this is my docker-compose.yml (over portainer stack)
```
version: "3.8"
services:
  olivetin:
    container_name: olivetin
    image: jamesread/olivetin:2024.11.18
    user: root # wichtig für 'docker exec... Befehle in anderen Containern'
    volumes:
      - cfg:/config
      - /var/run/docker.sock:/var/run/docker.sock # wichtig für 'docker exec... Befehle in anderen Containern'
    ports:
      - "1337:1337"
    restart: unless-stopped

volumes:
  cfg:
```

**Your config.yaml**

```
# There is a built-in micro proxy that will host the webui and REST API all on
# one port (this is called the "Single HTTP Frontend") and means you just need
# one open port in the container/firewalls/etc.
#
# Listen on all addresses available, port 1337
listenAddressSingleHTTPFrontend: 0.0.0.0:1337

# Choose from INFO (default), WARN and DEBUG
logLevel: "DEBUG"

# Checking for updates https://docs.olivetin.app/update-checks.html
checkForUpdates: false

pageTitle: PL-Aktionen
showFooter: false

# Actions are commands that are executed by OliveTin, and normally show up as
# buttons on the WebUI.
#
# Docs: https://docs.olivetin.app/create-your-first-action.html
actions:
  # This uses `popupOnStart: execution-dialog-stdout-only` to simply show just
  # the command output.
  - title: Checke Speicherplatz
    icon: disk
    shell: df -h /media
    popupOnStart: execution-dialog-stdout-only
    acls:
      - Authentik-Admins
#      - e1ke

authRequireGuestsToLogin: true # Optional - depends if you want to "disable" guests.

authOAuth2RedirectURL: "https://olivetin.MYDOMAIN.de/oauth/callback"
authOAuth2Providers:
  authentik:
    name: authentik
    title: Authentik
    clientID: "GW.......aHj"
    clientSecret: "3yOk.....................iZUjhFVv9O4BZzoi84xOpK2Y1gHzihyyMxkv5"
    authURL: "https://auth.MYDOMAIN.de/application/o/authorize/"
    tokenURL: "https://auth.MYDOMAIN.de/application/o/token/"
    whoamiURL: "https://auth.MYDOMAIN.de/application/o/userinfo/"
    usernameField: "preferred_username"
    icon: <iconify-icon icon="simple-icons:authentik"></iconify-icon>


#defaultPermissions:
#  view: true
#  exec: false
#  logs: false

accessControlLists:
  - name: Authentik-Admins
    matchUsergroups:
      - Authentik-Admins
    permissions:
      view: true
      exec: true
  - name: e1ke
    matchUserNames:
      - demo-admin
    permissions:
      view: true
      exec: true


```

**OliveTin logs**

here's my olivetin log when trying to login with authentik:
```
level="debug" msg="Found OAuth2 state: &{providerConfig:0xc000218a20 providerName:authentik Username:demo-praxismanager Usergroup:}"
level="debug" msg="UserFromContext" acls="[]" provider="oauth2" usergroup="" username="demo-praxismanager"
level="warning" msg="Zero actions found for user" acls="[]" availableActions="4" provider="oauth2" usergroup="" username="demo-praxismanager"
level="debug" msg="UserFromContext" acls="[]" provider="oauth2" usergroup="" username="demo-praxismanager"
```

**olivetin_scop in Authentik**
```
groups = [group.name for group in user.ak_groups.all()]
return {
    #"username": request.user.name,
    #"providerName": "authentik",
    "usergroup": ",".join(groups)
}
```

**Comment by jamesread** [comment]
Hey, so I'm not sure how I missed this when adding the OAuth code, but it was only pulling the username from the userinfo api. 

Could you upgrade to 2024.11.24, and set the UserGroupField on the provider, and try again? I didn't have a chance to test it, but it should work.

**Comment by e1ke** [comment]
Hi James, thank you very much. I will update, test and report ASAP

**Comment by ad3m3r5** [comment]
@jamesread 
Does the value returned from Authentik/Oauth2 for the attribute name `userGroupField` need to be comma separate group names?

Such as `"usergroup1, usergroup2, olivetin-users"`, or can OliveTin take the array from the standard `groups` attribute and join them itself?

**Comment by jamesread** [comment]
Actually neither, I just did a quick cheap ability to grab a single field usergroup, like primary_group. 

However, that design is a bit dumb - it certainly makes sense to be able to take in a list of groups. I'll get my authentik test environment going again tonight and look at options. 

I should eventually add support for oidc, I'm not sure if that covers groups as part of the userinfo call in the standard. 

Sorry, just doing family stuff at the weekend right now, so quickly replying from my phone. I'll have more time this evening.

**Comment by ad3m3r5** [comment]
No need for apology, enjoy the weekend!

I did some testing between Authentik and OliveTin, and got it to work for a single group - 

For a single group to work between the two, I chose to map the first Authentik group that starts with "olivetin" to the oauth attribute of `olivetin_group`. For my setup, this happens to be the group `olivetin-users`.

### In Authentik:
`Admin Interface > Customization > Property Mappings > Create > Scope Mapping`
- Name: `olivetin-group-mapping`
- Scope Name: `olivetin-group-mapping`
- Expression:
```
def find_first_group(arr, prefix):
    for group in arr:
        if group.startswith(prefix):
            return group
    return None

groups = [group.name for group in user.ak_groups.all()]

group_prefix = "olivetin"
olivetin_group = find_first_group(groups, group_prefix)

return {
    "olivetin_group": olivetin_group or "guest"
}
```

`Admin Interface > Applications >  Providers > {Your Provider} >Edit > Advanced protocol settings > Scopes`
- Add `olivetin-group-mapping` to `Selected Scopes`


### In OliveTin config.yaml
```
...
accessControlLists:
  - name: users
    matchUserGroups:
      - users
      - olivetin-users
    permissions:
      view: true
      exec: true
      logs: false
    addToEveryAction: true

authOAuth2Providers:
    ...
    userGroupField: "olivetin_group"
...
```
