### ISSUE TITLE
When I executed on webhook, I got an error of  “ACL check failed. Blocked from executing.  ”

### ISSUE THREAD

**Issue by Gitsifu** [OliveTin/OliveTin#489]
**Describe the bug**
```
curl -X POST "http://xxxx:1337/api/StartAction" -d '{"actionId": "deploy_web", "arguments": [{"name": "branch", "value": "dev"}]}'
```

How do I need to pass parameters to authenticate permissions？

**Comment by jamesread** [comment]
Heya, 

Do you presumably have authentication turned on, and defaultPermissions set to false? If so what type of auth - OAuth, JWT, etc? You would need to authenticate using that method.

**Comment by Gitsifu** [comment]
@jamesread Here is my configuration file。I want to authenticate using by Local Users Login. I need to use webhook. How do I pass parameters? 
```yaml
actions:
  - title: "deploy_web"
    id: deploy_web
    acls:
      - admins
    popupOnStart: execution-dialog
    shell: sh /app/olivetin/config/deploy-web.sh -b {{ branch }} -u $OT_USERNAME
    timeout: 600
    icon: '<img src = "custom-webui/icons/debug4.gif" style = "width: 3.5em;" />'
    arguments:
      - name: branch
        title: Branch
        default: dev
        description: 
        choices:
          - title: dev
            value: dev
          - title: master
            value: master

defaultPermissions:
  view: false
  exec: false
  logs: true
accessControlLists:
  - name: admins
    matchUsernames:
      - wsf
      - fcc
    permissions:
      view: true
      exec: true
    addToEveryAction: true

authLocalUsers:
  enabled: true
  users:
    - username: wsf
      password: $argon2id$v=19$m=65536,t=4,p=32$0rFMTWpOoRFhzVwRtwuHSA$KOpWOXPbL/5fQ3UrMNV3Sq1FuHXqZC78I9eD0Dnu1m8

    - username: fcc
      password: $argon2id$v=19$m=65536,t=4,p=32$TbDpoTO28zK6oBbugWYPzA$vU0mWtEhhfZea7dduLLL9M6WMZbQdaBF9rG2dXzAlvs
```
