### ISSUE TITLE
Is long text input supported？

### ISSUE THREAD

**Issue by FreezeJ** [OliveTin/OliveTin#490]
Hello,

I would like to use OliveTin to create a "toolbox". It needs to support long text input to complete its information entry. 

**For example:**
1. Using combinations of commands such as grep, sort, awk, and uniq to extract key information (such as IPs) from long texts.
2. Batch-check if SSL certificates for domains have expired, where each line in the long text represents a domain.

I reviewed the official documentation but couldn't find similar functionality. My idea is to add an Argument type, such as "filename", rendered as a textarea, to save and update a long text input to a specified path. My script could then use this filename as an input parameter.

config.yaml:
```yaml
  - title: check domains SSL
    icon: smile
    shell: python3 ssl_check.py {{ filePath }}
    arguments:
      - name: filePath
        type: filename
        path: "/path/of/file"
    popupOnStart: execution-dialog-stdout-only
```

Rendered as a textarea:
![企业微信截图_17334485026783](https://github.com/user-attachments/assets/829e8e10-5318-4fac-91da-0c5418d6422f)

**Comment by jamesread** [comment]
Heya @FreezeJ , thanks for your patience. I just added support for textboxes via `type: raw_string_multiline` (textboxes are not validated).

**Comment by jamesread** [comment]
Hey @FreezeJ , release 2025.2.19 now includes this feature. Docs are here: https://docs.olivetin.app/arg-textarea.html

**Comment by FreezeJ** [comment]
@jamesread I upgraded the version and tested the feature, it works great! 👍 


Below is my configuration, it will store long text and use a script to read the content of this specified file.
```yaml
...
  - title: check domains SSL
    id: multi_check_ssl
    shell: echo "{{domain_list}}" > /etc/OliveTin/text/domains.txt && python3 /etc/OliveTin/script/multi_check_ssl.py
    # https://icon-sets.iconify.design/
    icon: <iconify-icon icon="mdi:web-check"></iconify-icon>
    timeout: 100
    popupOnStart: execution-dialog-stdout-only
    arguments:
      - name: domain_list
        title: domain_list
        type: raw_string_multiline
...
```
