### ISSUE TITLE
[feat] New `executeMultipleActions` ?

### ISSUE THREAD

**Issue by accforgithubtest** [OliveTin/OliveTin#492]
Would you pls consider a feature request for a new `executeMultipleActions` which would be able to call a list of other existing actions by id ? 

While it is possible to chain few actions using `shellAfterCompleted`, it does not allow for much flexibility, and also the same bits of code is being repeated even when a separation action already exists in the file.

It would be awesome if I could
```yaml
actions:

  - title: Turn Off TV
    id: turn_off_tv
    shell: ...

  - title: Turn Off Air Con
    id: turn_off_ac
    shell: ...

 - title: Turn On Air Con
    id: turn_on_ac
    shell: ...
  
  - title: Shut Down Desktop
    id: turn_off_pc
    shell: ...

  - title: Turn Off Lights
    id: turn_off_lights
    shell: ...

  - title: Enable Security Alarms
    id: turn_on_sec_alarm
    shell: ...

  - title: Movie Time
    id: movie_time
    executeMultipleActions:
    - turn_off_lights
    - turn_on_ac
    
  - title: Out Of Home
    id: out_of_home
    executeMultipleActions:
    - turn_on_sec_alarm
    - turn_off_lights
    - turn_off_tv
    - turn_off_ac
    - turn_off_pc
```
