### ISSUE TITLE
Restrict all actions, but few allowed for non-logged in users

### ISSUE THREAD

**Issue by accforgithubtest** [OliveTin/OliveTin#493]
I need some help on approaching ACL. I went thru the docs and seemed straight forward. However, I have not been able to get what I wanted.

I have a set up with lldap and authelia with 2fa, and is this set-up is confirmed as working fine with other applications.

What I want in OliveTin -
1. Few actions to be executable by Anonymous / non-logged-in users with no groups / acls.
1. All other actions to be restricted to 'admin'

Here is what I came up with, but its not working. Looks like only the restricted settings are applied and all actions are not available to non logged in users.

```yaml
# LLDAP Groups Set-up
authHttpHeaderUsername: "Remote-User"
authHttpHeaderUsergroup: "Remote-Groups"

# defaultPermissions:
#   view: false
#   exec: false
#   logs: false

accessControlLists:
  - name: public
    permissions:
      view: true
      exec: true
  - name: admin
    matchUsergroups:
      - admin
    permissions:
      view: true
      exec: true
    addToEveryAction: true

actions:

  - title: Test Action A
    icon: "&#127910;"
    shell: docker restart appName
    acls:
    - public

  - title: Test Action B
    icon: "&#127910;"
    shell: docker restart appName
    acls:
    - admin
```

I want action A to be accesible by everyone, and action B to be restricted to logged in users with 'admin' groups.

Can you pls suggest me what I need to do get the test action A to be publicly accessible ?

**Comment by jamesread** [comment]
Heya, quick reply while I'm on my phone. 

Thd public acl doesn't yet match anything, add "matchUsernames: - guest"

Also, get it to match the aminds group too.

Adjusted config below; 

```yaml
# LLDAP Groups Set-up
authHttpHeaderUsername: "Remote-User"
authHttpHeaderUsergroup: "Remote-Groups"

# defaultPermissions:
#   view: false
#   exec: false
#   logs: false

accessControlLists:
  - name: public
    permissions:
      view: true
      exec: true
# added
    matchUsernames: 
      - guest
    matchUsergroups:
      - admin
# added 

  - name: admin
    matchUsergroups:
      - admin
    permissions:
      view: true
      exec: true
    addToEveryAction: true

actions:

  - title: Test Action A
    icon: "&#127910;"
    shell: docker restart appName
    acls:
    - public

  - title: Test Action B
    icon: "&#127910;"
    shell: docker restart appName
    acls:
    - admin
```

**Comment by accforgithubtest** [comment]
thanks for the quick reply @jamesread !
I dint realize that guest was a default user name for anonymous users. 

After using the above, I still have issues. 
Are you able to suggest if I am missing anything obvious, or any tips on what I should be looking at next to fix this please?

* I see the logged in user name on the top right near the profile pic. OliveTin seems to have picked up the user name and groups from the headers.
* All public actions are not even visible anymore.
* All Admin only actions are showing red buttons with "Action not found: <action title>"
* In the logs, I see 
```json
{
  "level": "warning",
  "msg": "Zero actions found for user",
  "acls": "[]",
  "availableActions": "77",
  "provider": "http-header",
  "usergroup": "admin,users",
  "username": "admin"
}
```
* I have a few cron scheduled actions as well. These were working fine without the ACL. Now they are failing too with below logs
```
{
  "level": "warning",
  "msg": "ACL check failed. Blocked from executing.",
  "actionTitle": "Every 5 Mins"
}
```

**Comment by accforgithubtest** [comment]
I am also noticing that
1. Keeping this enabled in the config, I see above issues.
```yaml
defaultPermissions:
  view: false
  exec: false
  logs: false
```
1. Commenting out the defaultPermissions, Everything is accessible to everyone, logged in or not. So no acl is getting applied without defaultPermissions.

Ideally, should the `defaultPermissions` be enabled or disabled for [this kind of set up](https://github.com/OliveTin/OliveTin/issues/493#issuecomment-2527162362)?
