### ISSUE TITLE
ACLS not working

### ISSUE THREAD

**Issue by beuker81** [OliveTin/OliveTin#494]
Hi,
I'm new to OliveTin and I love this simple approach of OliveTin. I came already far with everything but one the ACLs are just not working.
I tried to add authentication and acls to my configuration. Below is my configuration but when I login as the user I don't see the actions I can perform. Just a blank screen. I also asked on Discord and there was suggested that this is maybe a bug? If not how does I make this work?
Thanks!

```yaml
listenAddressSingleHTTPFrontend: 0.0.0.0:1337

logLevel: "INFO"
showNavigation: false
showFooter: false
checkForUpdates: false

actions:
  - title: Ping the PC
    acls:
      - admins
    shell: ping -c 1 <IP>
    icon: ping
    popupOnStart: default

  - title: Start / WOL PC
    acls:
      - admins
    icon: start
    shell: /usr/bin/wol <MAC>
    popupOnStart: default

  - title: Shutdown PC
    acls:
      - admins
    shell: /usr/bin/net rpc -S <IP> -U <USER>%<PASSWD> shutdown -t 1 -f
    icon: stop
    popupOnStart: default

  - title: Reboot PC
    acls:
      - admins
    shell: /usr/bin/net rpc -S <IP> -U <USER>%<PASSWD> shutdown -t 1 -f -r
    icon: restart
    popupOnStart: default

defaultPermissions:
        view: false
        exec: false
        logs: false

authRequireGuestsToLogin: true

accessControlLists:
  - name: admins
    matchUsergroups:
      - admins
    permissions:
      view: true
      exec: true
      logs: true
    addToEveryAction: true

authLocalUsers:
  enabled: true
  users:
    - username: <user>
      password: <password>
      groups:
        - admins
```
