### ISSUE TITLE
Scheduled action not worked as expected

### ISSUE THREAD

**Issue by tissoni** [OliveTin/OliveTin#496]
Hello folks, i have this action to schedule a deprovision, currently this writes the date and time correctly to a file called  /etc/OliveTin/deprovision-calendar.yaml, this is working as expected:
```
  - title: Schedule Deprovision
    shell: echo '- {{ when }}+00:00' >> /etc/OliveTin/deprovision-calendar.yaml
    arguments:
    - name: when
      title: When?
      type: datetime
```
But this is not working, when the date and time is the same, this file is not beeing updated with the text Starting deprovision.

  ```
- title: start Deprovision
    shell: echo 'Starting deprovision! ' >> /etc/OliveTin/deprovision-calendar.yaml
    execOnCalendarFile: /etc/OliveTin/deprovision-calendar.yaml  

```

This actions has the same format that the documentation https://docs.olivetin.app/action_execution/oncalendar.html
