### ISSUE TITLE
Can I add icons in containers status panel

### ISSUE THREAD

**Issue by touero** [OliveTin/OliveTin#498]
I installed OliveTin in docker, and I pulled the latest image.

I browsed the [Container Control Panel](https://docs.olivetin.app/container-control-panel.html#container-control-panel) while customizing the icons and it worked perfectly

But I want to add an icon to the docker container status panel on the far left.

I want the running status to display an icon, and exited to be another icon.

Do the existing conditions allow me to do this?

![image](https://github.com/user-attachments/assets/b095a1d1-834f-4467-93aa-60609d764f01)

**Comment by touero** [comment]
I found a solution. Just add an icon to the title.

```yaml
dashboards:
  - title: DockerContainers
    contents:
      - title: ' '
        entity: container
        type: fieldset
        contents:
          - type: display
            title: |
              <iconify-icon icon="vscode-icons:file-type-docker2" width="3em" height="3em"></iconify-icon><strong>{{ container.Names }}</strong>{{ container.Image }}
          - title: 'Start {{ container.Names }}'
          - title: 'Stop {{ container.Names }}'
          - title: 'Restart {{ container.Names }}'
          - type: display
            title: |
              <iconify-icon icon="logos:statuspage" width="2.71em" height="2em"></iconify-icon><strong>{{ container.State }}</strong>{{ container.Status }}


```
