### ISSUE TITLE
Add the ability to preload a field value from a yaml file into an input field

### ISSUE THREAD

**Issue by InnovoDeveloper** [OliveTin/OliveTin#505]
I have created some arguments with input texttypes.  Works great for submitting some information to my backend script that then writes a file with these values.  Is it possible that when this action is loaded, that it can also read these values and pre-populate them in place of the static default value

The idea is to basically achieve is a web form that can be preloaded with previously entered information so that the user doesn't have to start with the same defaults values always.

A good use case for this would also be read and write network address information for systemd networkd

read a file from yaml
```yaml
- firstName: George
  lastName: Smith
  playerName: MightySmith
```

then make those the default values for matching input

```yaml
title: Setup Names
    shell: set-name {{ firstName }} {{ lastName }} {{ playerName }}
    icon: icon
    arguments:
      - name: firstName
        description: Add First Name
        title: {{ value from yaml file matching firstName }}
        default: John
        type: ascii_identifier
      - name: lastName
        description: Add last Name
        title: {{ value from yaml file matching lastName }}
        default: Smith
        type: ascii_identifier
      - name: playerName
        description: Add Vanity Player Name
        title: {{ value from yaml file matching playerName }}
        default: vanity name
        type: ascii_identifier
```

It would also be nice that if the input argument is a drop down or select, the item is preselected

**Comment by casanoe** [comment]
Hello all,
I have a similar need. I'd like to be able to pre-populate the default value in the arguments, using a value of entity file.
The aim is to edit a file for example.

In my case, the piece of code  : 
```
- title: Edit {{ entityfile.ID }}
    entity: entityfile
    shell: update_entityfile.sh {{ entityfile.ID }} {{ COMMAND }}
    arguments:
      - name: COMMAND
        default: '{{ entityfile.CMD}}'
```

It would be great if you could take this into account.
Thanks, and I wish you all the best with this fantastic solution !

**Comment by jamesread** [comment]
This has been addressed.

Argument `default` values are now template-parsed with entity context, so you can preload form fields from entity (YAML) data.

Example:

```yaml
entities:
  - file: names.yaml
    name: names

actions:
  - title: Setup Names
    entity: names
    shell: set-name {{ .Arguments.firstName }} {{ .Arguments.lastName }} {{ .Arguments.playerName }}
    icon: icon
    arguments:
      - name: firstName
        description: Add First Name
        default: '{{ .CurrentEntity.firstName }}'
        type: ascii_identifier
      - name: lastName
        description: Add Last Name
        default: '{{ .CurrentEntity.lastName }}'
        type: ascii_identifier
      - name: playerName
        description: Add Vanity Player Name
        default: '{{ .CurrentEntity.playerName }}'
        type: ascii_identifier
```

This also works for dropdowns: set `default` to the value that should be preselected.

Legacy templates such as `{{ entityfile.field }}` are still migrated to `{{ .CurrentEntity.field }}`.

Relevant change: argument defaults began being templated with entity data in `b37f035e` (Jan 2026).

Closing as fixed.
