### ISSUE TITLE
Manual installation guide (.tar.gz) incomplete/outdated

### ISSUE THREAD

**Issue by pawlowskatze** [OliveTin/OliveTin#512]
**Describe the bug**
Since the native Fedora .rpm package still uses 2022 versions, I decided to go for the manual install.
However: The manual installation guide provided at https://docs.olivetin.app/install-targz.html doesn't (fully) work (any longer).
Specifically, it lacks the details about what to do regarding the contents of the "var" folder after unpacking.
_Side-note: I was eventually able to make OliveTin work by manually fiddling around its pieces after install_

**To Reproduce**
1. Follow the manual installation guide 
2. Check output of `systemctl status OliveTin.service`  (e.g. where it claims to be unable to find entities)
3. Try to run any helper (e.g. get themes) from the webUI and check logs/systemctl (-> "command not found")

**Expected behavior**
A tested, updated full-step guide including what to do with each component/folder of the .tar.gz.
This should specifically include
- chown/chmod advise 
- respect the fact that the current .tar.gz base already contains a config.yaml
- where to put the helper scripts from var/helper-actions (in my case, they needed to be at /usr/local/bin

I also noticed that at some point, OliveTins suddenly started to expect its config.yaml in /config (instead of /etc/OliveTin...)

**Screenshots**
none provided.

**Additional context**
Tested on a Fedora 42 server.

**Comment by jamesread** [comment]
Heya @pawlowskatze , thanks for taking the time to report this issue. 

**Why is the Fedora package so old?**
It pains me that the OliveTin package in the Fedora repositories is so old, because I'm so proud of getting it into a Linux distribution - which I personally use as my daily driver!

However, Fedora famously runs a secure build system without internet access, meaning that all Go dependencies need to be available in the Fedora repositories. Back in 2022 I had to add a dependency for JWK Signing that wasn't available, and it broke the Fedora builds. Since then, I believe the Fedora build system has added support for dependency vendoring (including the dependency in sources), which is a very sensible step. I'll have to ping my good friend @Fale when he has some time to remind mme how to update the package and try this new approach with dep vendoring (I need to start by reading the docs)! 

**Documentation fixes as requested**

The .tar.gz installation instructions don't get used very often, I think you're actually the first person to comment on them. However, good comments, all good suggstions, I've updated the page here - could you review?

https://docs.olivetin.app/install-targz.html

Thanks again for your time!

**Comment by pawlowskatze** [comment]
Hi @jamesread - thank you very much for the swift reply and your efforts to fix my observations.
Neither I expected this to happen at all, nor even that fast. ❤ 
_I actually was afraid of not getting an answer at all and that OliveTin probably did become "abandonware" in the meanwhile._

Regarding the updated manual: It's almost perfect: Only step 5 ("Create a config.yaml...") is no longer required since it got superseded by step 2a ("Copy the config.yaml..."). Other than that, I'm perfectly satisfied 🥰 

While we're at it, here's one more question:
Sorry if this is already covered somewhere in the docs, but is there a way to include a **variable inside an actions title**?
I'm having a cron job that runs on daily basis which creates log-like files. These accumulate over time and I want to be able to have an action that deletes them, yet want to see the number of files in the action title like "Delete {{files_count}} log file(s)" where {{files_count}} would be provided by e.g. `ls- al /tmp/mylog* | wc -l`
The script to provide the variable value could probably be run "on load" of the OliveTin web interface, meaning when I refresh the page the script gets triggered to update the title...?

_I could of course extend my own scripts' logics to take care of automatically deleting these files, but I sometimes need to check their contents first, that's why I leave them on disk at first hand._
If you feel I should create a feture request, I'd be happy to file that!

On a side-note: I also struggled to understand how to provide the unicode icon identifier for an action but was able to find out how to convert e.g. `"U+263A"` (from "charmap") into the required notation `"&#x263A"`. It's probably self-explaining for people with a dev background but it wasn't that obvious to me, so it might be worth mentioning in the docs too? I'd even offer to do that if I'm allowed to...

Lastly, again: Thank you very much!

**Comment by jamesread** [comment]
@pawlowskatze you're most welcome :-) 

> I actually was afraid of not getting an answer at all and that OliveTin probably did become "abandonware" in the meanwhile.

Oh no! What actually gave you that impression? Does the project somehow look abandoned? I guess I've not been so hot on GitHub issues recently. 

> Regarding the updated manual: It's almost perfect: Only step 5 ("Create a config.yaml...") is no longer required since it got superseded by step 2a ("Copy the config.yaml..."). Other than that, I'm perfectly satisfied 🥰

Ah yes, I just pushed a fixed for that :-) 

> While we're at it, here's one more question:
Sorry if this is already covered somewhere in the docs, but is there a way to include a variable inside an actions title?
I'm having a cron job that runs on daily basis which creates log-like files. These accumulate over time and I want to be able to have an action that deletes them, yet want to see the number of files in the action title like "Delete {{files_count}} log file(s)" where {{files_count}} would be provided by e.g. ls- al /tmp/mylog* | wc -l
The script to provide the variable value could probably be run "on load" of the OliveTin web interface, meaning when I refresh the page the script gets triggered to update the title...?

Yeah sure thing. I just wrote this and tested it. It's not super pretty, but I tried to write it in a way that makes it easy for you to edit and update to meet your needs. 

```yaml
actions:
  - title: check log directory
    hidden: true
    shell: |
      function addDirectory {
        COUNT=$(ls -l $1 | wc -l)
        echo "- directory: $1" >> /etc/OliveTin/entities/directories.yaml
        echo "  count: $COUNT" >> /etc/OliveTin/entities/directories.yaml
      }

      truncate -s 0 /etc/OliveTin/entities/directories.yaml
      addDirectory /var/log/
      addDirectory /home/xconspirisist/logs
    execOnStartup: true
    execOnCron: "* * * * *"

  - title: clean {{ log_directory.directory }} ({{log_directory.count }} files)
    shell: |
      echo "Removing all files in {{ log_directory.directory }}"
    entity: log_directory

entities:
  - name: log_directory
    file: /etc/OliveTin/entities/directories.yaml

dashboards:
  - title: Log Actions
    contents:
      - entity: log_directory
        type: fieldset
        contents:
          - title: clean {{ log_directory.directory }} ({{log_directory.count }} files)
```

When rendered, that gives buttons that look like this;

![Image](https://github.com/user-attachments/assets/5997fa4d-a300-4ba0-8923-f39a19f622cb)

Is that what you had in mind?
