### ISSUE TITLE
Action name is identifier after evaluation

### ISSUE THREAD

**Issue by gander** [OliveTin/OliveTin#527]
This is not obvious, and I wasted a lot of time to figure it out. There is also nothing about it in the documentation. I have two different actions:

```yaml
- title: Restart {{ project.title }}
  shell: restart-project.sh {{ project.title }}

- title: Restart {{ container.Names }}
  shell: docker restart {{ container.Names }}
```

In the projects view, only 3 out of 7 projects were displayed, and I couldn't figure out why. Until I noticed that 4 of these projects are named exactly the same as containers, and thus I understood that actions must take the name after the variable evaluation, not in the source form.

---

After changing to:

```yaml
- title: Restart project {{ project.title }}
  shell: restart-project.sh {{ project.title }}

- title: Restart {{ container.Names }}
  shell: docker restart {{ container.Names }}
```

finally all containers and all projects are displayed correctly.... BUT BUG is not solved that way! It's only workaround.
