### ISSUE TITLE
Config change does not trigger live reload (Kubernetes)

### ISSUE THREAD

**Issue by okgolove** [OliveTin/OliveTin#531]
**Describe the bug**
Live reload does not work when config.yaml file is mounted from Kubernetes configmap

**To Reproduce**
1. Apply simple olivetin deployment and configmap:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: olivetin
  namespace: olivetin
data:
  config.yaml: |
    actions:
      - title: Restart environment
        shell: echo restart
        timeout: 10
---
apiVersion: v1
kind: Service
metadata:
  name: olivetin
  namespace: monitoring-clients
spec:
  selector:
    app.kubernetes.io/instance: olivetin
    app.kubernetes.io/name: olivetin
  ports:
    - name: http
      port: 1337
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: olivetin
  namespace: olivetin
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: olivetin
      app.kubernetes.io/name: olivetin
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: olivetin
        app.kubernetes.io/name: olivetin
    spec:
      containers:
        - image: ghcr.io/olivetin/olivetin:2025.2.19
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: http
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 1
          name: olivetin
          ports:
            - containerPort: 1337
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: http
              scheme: HTTP
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 1
          volumeMounts:
            - mountPath: /config
              name: config
      volumes:
        - configMap:
            name: olivetin
          name: config
```
2. Edit configmap using `kubectl edit configmap olivetin`, e.g. change action name and save
3. Validate config.yaml inside the pod has been updated:
```shell
kubectl exec -t -i deploy/olivetin -- cat /config/config.yaml
```
4. Port-forward and check Web UI:
```shell
kubectl port-forward svc/olivetin 1337
```

**Expected behavior**
Action name in Web UI is updated, reload log appeared:
```
INFO Config file changed:WRITE         "/config/config.yaml"
```

**Actual behavior**
No update log, action name is still the same
