### ISSUE TITLE
Unselected (blank) Dropdown arguments may cause unexpected behavior

### ISSUE THREAD

**Issue by aholeinthehead** [OliveTin/OliveTin#532]
**Describe the bug**
When an action is defined with a dropdown/choices argument, the resulting form allows the user to submit their response without choosing a response.  This can result in security and stability issues.

**To Reproduce**

- Assume an entity like this:
```yaml
# yaml list of retired sites.  
# Included as 'retired_sites' in our OliveTin entities
- site_directory: customer1
  site_id: customer1-20230103a
- site_directory: customer33
  site_id: customer33-20241121a
- site_directory: customer44
  site_id: customer44-20191225a

```

- Define an action like this:

```yaml
  - title: Remove site directory
    shell: 'rm -rf "/customer_sites/{{ SiteDirectory }}"'
    popupOnStart: execution-dialog
    arguments:
      - name: SiteDirectory
        entity: retired_sites
        title: Retired Site directory
        choices:
          - title: '{{retired_sites.site_directory}} ({{retired_sites.site_id}})'
            value: '{{retired_sites.site_directory}}'

```

When executed, if the user makes no selection, the command is run as:

`rm -rf "/customer_sites/"`

This deletes all customer sites.  Not just the selected, retired one.

**Expected behavior**
The form should require a selection, refusing to continue if none is made.

**Additional context**
A workaround is possible by using an external script to perform sanity checking.  However, this greatly complicates the implementation.  It's _so close_ to being safe for use.  It just needs one little safeguard.

**Suggested fix**
A boolean option for the `choices` map,  `required: (true|false)` would preserve the current functionality, but allow OliveTin admins to define this action to behave in a more controlled, predictable way.
