### ISSUE TITLE
Add simple nav-bar with links to other resources

### ISSUE THREAD

**Issue by strazto** [OliveTin/OliveTin#54]
**Is your feature request related to a problem? Please describe.**

I think it'd be useful to be able to include arbitrary links on the olivetin menu, to accomodate for users who may have navigated there from some other page and wish to navigate back.

**Describe the solution you'd like**

Allow some buttons to be specified without any action, but instead with a `url` field, which navigates to some url

**Describe alternatives you've considered**

Functionality similar to https://github.com/bastienwirtz/homer , but with more limited scope - some buttons just let us go to other pages.

**Additional context**

This might also be useful as a more simple way to address #35 - Users would be able to navigate between olivetin instances more conveniently.

**Comment by jamesread** [comment]
Hey @matthewstrasiotto , thanks for taking the time to write up this feature request. :-)

I've thought about doing this a few times, as it's so simple to do with just a few lines of code to get the initial feature working. 

However, I also want to avoid re-implementing homer/heimdall/organizrr, all which are pretty big and mature projects - it's not something OliveTin was intended to do. 

I'm willing to keep an open mind and would consider adding this, if we can think of sensible use cases. The "just incase someone clicks the wrong link and goes to OliveTin" isn't a great use case - as users would typically just use the browser's back button. 

At this stage I'm not convinced, but open to hearing more use cases where we think this would make sense.

**Comment by matthewstrasiotto** [comment]
> The "just incase someone clicks the wrong link and goes to OliveTin" isn't a great use case

The use-case I have in mind is more that extra navigability/discoverability is always a good thing. Though I agree that you don't want to re-implement homer/heimdall/organizrr, being able to easily navigate from a given page to any other is almost always a good thing. 

For example, on my blog https://straz.to/2021-09-08-docker-address-pools/ , there's a nav bar that lets us get to the blog home, as well as other projects. 

![image](https://user-images.githubusercontent.com/39424834/162677557-0f973a19-b4f4-477a-99c6-7165bdb627d2.png)

I also think that it might be a less-complex alternative to #35 - just host your priveleged + unpriveleged instances, and have a way to navigate between instances, or back to the home page.

This being said - to this end, maybe instead of making some buttons act as links instead of command triggers, it would make more sense to simply add a nav-bar, that can be configured similarly to other projects (homer, jekyll etc). 

Probably, copying [Homer's api](https://github.com/bastienwirtz/homer/blob/main/docs/configuration.md) would be sufficient:

```yaml
# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "Link 1"
    icon: "fab fa-github"
    url: "https://github.com/bastienwirtz/homer"
    target: "_blank" # optional html tag target attribute
  - name: "link 2"
    icon: "fas fa-book"
    url: "https://github.com/bastienwirtz/homer"
  # this will link to a second homer page that will load config from page2.yml and keep default config values as in config.yml file
  # see url field and assets/page.yml used in this example:
  - name: "Second Page"
    icon: "fas fa-file-alt"
    url: "#page2"
```

Or for a more tangible usecase:

```yaml
# imagine this instance is running at:
# https://olivetin.example.com
links:
  # Link back to the homepage
  - name: "Dashboard / Home"
    icon: "fab fa-home"
    url: "https://homer.example.com"
  # Link to the other olivetin instance, which might require more authorization
  # Or the actions are more complex / advanced
  - name: "Advanced / Priveleged Actions"
    icon: "fas fa-lock"
    url: "https://olivetin-admin.example.com"
  
```

This way the function & purpose of the different elements are more clearly dilineated - The dashboard of buttons executes commands, the nav-bar lets you navigate to some other resources.

I will revise this issue name to "Add simple nav-bar"

**Comment by jamesread** [comment]
Hey @matthewstrasiotto , after some further thought, and reading your comments a few times, I think this could be useful. 

Implementation guidance; 

* These links should probably be a new config object `AdditionalLink`, with a `Title`, `URL` and `Target`, and defined in https://github.com/OliveTin/OliveTin/blob/main/internal/config/config.go , and laid out something like this; 
.config.yaml
````
externalRestAddress: http://myserver/OliveTin
actions:
    - name: ....
    ...

additionalNavigationLinks: 
    - title: Duck Duck Go
      url http://ddg.gg
      target: _blank

    - title: Organizrr
      url: http://organizrr.webapps.example.com
      target: _blank
````

* To get the links to the browser, you'll need to copy them into `webUISettings` in https://github.com/OliveTin/OliveTin/blob/2d7157703ce2bc03de547b95b6b6f5e8b382b6ee/internal/httpservers/webuiServer.go#L46
* For now, can you add the links into the existing section-switcher as anchor (`<a href ... >`) elements, or you can choose to create a separate top nav bar. 

Functional requirements;

* Title, URL, and Target (for creating popup links if necessary). 
* Icons are optional, but no fontawesome thank you :-) 
* Behaves responsively, and nicely in small width layouts.
