### ISSUE TITLE
Config bugs when upgrade to 2025.x.xx

### ISSUE THREAD

**Issue by towerstreet** [OliveTin/OliveTin#542]
**Describe the bug**
Config bugs when upgrade to 2025.x.xx

**What need to be change in the config file?**

```
## 设置端口
listenAddressSingleHTTPFrontend: 0.0.0.0:9595

## 日志等级
logLevel: "INFO"

## 检查更新
checkForUpdates: false

## 网站标题
pageTitle: OliveTin

## 默认权限
defaultPermissions:
  view: true
  exec: false
  logs: false

## 用户权限
accessControlLists:
  - name: admins
    matchUsergroups:
      - admins
    permissions:
      view: true
      exec: true
      logs: true
    addToEveryAction: true

  - name: "cron" # https://docs.olivetin.app/exec-cron.html#_cron_and_acls
    matchUsernames:
      - cron
    permissions:
      exec: true
    addToEveryAction: true

## 本地用户 https://docs.olivetin.app/local-users.html#_option_a_using_olivetin_api
authLocalUsers:
  enabled: true
  users:
    - username: Towerstreet
      usergroup: admins
      password: $argon2id$v=19$m=65536,t=4,p=2$dtJ2EnTQIB7/sYtHhSBqkA$LrjOiKkfXPc+PbCJbxT2dBk4p+8uqkFbI/NJKliz5do

actions:
  # 整点报时
  - title: Date
    icon: <iconify-icon icon="svg-spinners:clock"></iconify-icon>
    shell: gotify push -t "OliveTin🕙" -p 6 --contentType text/markdown "# $(date +"%r")\n\n## $(date +"%A")\n\n## $(date +"%F")"
    execOnCron:
      - "0 * * * *"
    acls:
        - "cron"

  # 网络测试
  - title: Check Connect
    icon: <iconify-icon icon="svg-spinners:3-dots-scale"></iconify-icon>
    timeout: 100
    shell: gotify push -t "OliveTin🌐" -p 6 --contentType text/markdown "# Check Connect🌐\n\n$(sudo tsocks curl -I google.com --connect-timeout 10)\n\n---\n\n$(date +"%A %F %r")"
    execOnCron:
      - "0 * * * *"
    acls:
        - "cron"

  # APT升级
  - title: Apt Upgrade
    icon: <iconify-icon icon="line-md:upload-loop"></iconify-icon>
    timeout: 100
    shell: sudo apt update && sudo apt upgrade -y
    popupOnStart: execution-dialog-stdout-only

  # Snap升级
  - title: Snap Upgrade
    icon: <iconify-icon icon="line-md:upload-loop"></iconify-icon>
    timeout: 100
    shell: sudo snap refresh
    popupOnStart: execution-dialog-stdout-only

  # 查看硬盘空间
  - title: Check disk space
    icon: <iconify-icon icon="svg-spinners:blocks-wave"></iconify-icon>
    shell: df -h /media
    popupOnStart: execution-dialog-stdout-only

  # 查找文件
  - title: Find File
    icon: <iconify-icon icon="line-md:search"></iconify-icon>
    timeout: 100
    shell: sudo find {{ dir }} -name {{ name }} | tee /home/towerstreet/OliveTin.log
    shellAfterCompleted: gotify push -t "🔍OliveTin.log" -p 6 < /home/towerstreet/OliveTin.log
    popupOnStart: execution-dialog-stdout-only
    arguments:
      - name: dir
        title: 查找位置
        type: url
        default: /
        
      - name: name
        title: 文件名
        type: ascii_identifier

  # 运行命令脚本
  - title: Shell
    icon: <iconify-icon icon="svg-spinners:pulse-rings-2"></iconify-icon>
    timeout: 100
    shell: "{{ shell }}{{ choice }}"
    popupOnStart: execution-dialog-stdout-only
    arguments:
      - name: shell
        title: 命令
        type: very_dangerous_raw_string
      - name: choice
        title: 预设
        choices: 
          - title: Screenfetch
            value: screenfetch
          - title: IPTV-TVBOX.sh
            value: su - towerstreet -c /home/towerstreet/Storage/Github/IPTV-TVBOX.sh
          - title: IPTV-TVBOX-PUSH.sh
            value: su - towerstreet -c /home/towerstreet/Storage/Github/IPTV-TVBOX-PUSH.sh

  # 修改Version.md
  - title: Sed Version.md
    icon: <iconify-icon icon="svg-spinners:blocks-shuffle-2"></iconify-icon>
    shell: sudo sed -i 's/{{ app }} {{ version1 }}/{{ app }} {{ version2 }}/g' /home/towerstreet/Storage/Files/Version.md
    shellAfterCompleted: gotify push -t "Version.md" -p 6  --token AOkYtVh_qfCmR3C --contentType text/markdown < /home/towerstreet/Storage/Files/Version.md
    arguments:
      - name: app
        title: 名称
        choices:
          - value: Dpanel
          - value: Fileshelter
          - value: Synctv
          - value: Metube
          - value: Diun
          - value: RSSHub

      - name: version1
        title: 旧版本号
        type: very_dangerous_raw_string

      - name: version2
        title: 新版本号
        type: very_dangerous_raw_string

  # Gotify发布文件内容
  - title: Gotify Push Files
    icon: <iconify-icon icon="line-md:alert-twotone-loop"></iconify-icon>
    shell: gotify push -t "Gotify 📂" -p {{ priority }} --token ARkfp8ThlroeqTc {{ type }} < {{ file }}{{ choice }}
    arguments:
      - name: file
        title: 文件
        type: url

      - name: choice
        title: 预设
        choices:
          - value: /home/towerstreet/Storage/Docker/Gotify/Gotify.md
          - value: /home/towerstreet/Storage/Files/Version.md
          - value: /home/towerstreet/OliveTin.log

      - name: priority
        title: 优先级
        type: int
        default: 6

      - name: type
        title: 类型
        choices:
          - value: --contentType text/plain
          - value: --contentType text/markdown

  # Gotify通知
  - title: Gotify Push Mesage
    icon: <iconify-icon icon="line-md:alert-square-loop"></iconify-icon>
    shell: gotify push -t "Gotify ✉️" -p {{ priority }} --token ARkfp8ThlroeqTc --contentType text/markdown "# {{ title }}\n\n{{ message }}\n\n{{ picture }}"
    arguments:
      - name: title
        title: 标题
        type: very_dangerous_raw_string
        default: "Hello Markdown"

      - name: message
        title: 内容
        type: very_dangerous_raw_string
        default: "This is a *Markdown* message with **bold** and _italic_ text."

      - name: picture
        title: 图片
        type: very_dangerous_raw_string
        default: 

      - name: priority
        title: 优先级
        type: int
        default: 6

  # 查看Docker Container日志
  - title: Docker Container Logs
    icon: <iconify-icon icon="svg-spinners:bouncing-ball"></iconify-icon>
    timeout: 100
    shell: sudo docker logs {{ container }} | tee /home/towerstreet/OliveTin.log
    popupOnStart: execution-dialog-stdout-only
    arguments:
      - name: container
        title: Container Name 🔍
        entity: container
        choices:
          - value: '{{ container.Names }}'
            title: '{{ container.Names }}'

  # 重启Docker Container
  - title: Restart Docker Container
    icon: <iconify-icon icon="svg-spinners:90-ring-with-bg"></iconify-icon>
    timeout: 100
    shell: sudo docker restart {{ container }}
    popupOnStart: execution-dialog-stdout-only
    arguments:
      - name: container
        title: Container Name 🔄️
        entity: container
        choices:
          - value: '{{ container.Names }}'
            title: '{{ container.Names }}'

  # 重启Snap
  - title: Restart Snap
    icon: <iconify-icon icon="svg-spinners:12-dots-scale-rotate"></iconify-icon>
    timeout: 100
    shell: sudo snap restart {{ snap }}
    popupOnStart: execution-dialog-stdout-only
    arguments:
      - name: snap
        title: Snap Name 🔄️
        choices:
          - value: docker
          - value: nextcloud
          - value: plexmediaserver

  # 重启Service
  - title: Restart Service
    icon: <iconify-icon icon="svg-spinners:bars-fade"></iconify-icon>
    timeout: 100
    shell: sudo systemctl restart {{ service }}
    popupOnStart: execution-dialog-stdout-only
    arguments:
      - name: service
        title: Service Name 🔄️
        choices:
          - value: alist
          - value: aria2
          - value: nginx
          - value: OliveTin

  # 重设OliveTin
  - title: OliveTin Config
    icon: <iconify-icon icon="svg-spinners:bars-rotate-fade"></iconify-icon>
    timeout: 100
    shell: sudo cp /home/towerstreet/Storage/Files/OliveTin.yaml /etc/OliveTin/config.yaml && sudo systemctl restart OliveTin
    arguments:
      - type: confirmation
        title: ⚠️Are you sure❓

## Crontab
  - title: Restart Argus
    icon: <iconify-icon icon="svg-spinners:90-ring"></iconify-icon>
    shell: sudo docker restart argus
    timeout: 100
    popupOnStart: execution-dialog-stdout-only
    hidden: true
    execOnCron: '5 */2 * * *'
    acls:
        - "cron"

  - title: Restart Fusion
    icon: <iconify-icon icon="svg-spinners:90-ring"></iconify-icon>
    shell: sudo docker restart fusion
    timeout: 100
    popupOnStart: execution-dialog-stdout-only
    hidden: true
    execOnCron: '1,31 * * * *'
    acls:
        - "cron"

  - title: Git Pull IPTV-TVBOX
    icon: <iconify-icon icon="svg-spinners:gooey-balls-2"></iconify-icon>
    shell: su - towerstreet -c /home/towerstreet/Storage/Github/IPTV-TVBOX.sh | tee /home/towerstreet/OliveTin.log
    shellAfterCompleted: gotify push -t "🤖Git Pull IPTV-TVBOX" -p 6  --token A-vdZfK6FZ279sl < /home/towerstreet/OliveTin.log
    timeout: 100
    popupOnStart: execution-dialog-stdout-only
    hidden: true
    execOnCron: '20 */6 * * *'
    acls:
        - "cron"

## Dashboard
  - title: Start {{ container.Names }}
    icon: <iconify-icon icon="line-md:lightbulb-filled"></iconify-icon>
    timeout: 100
    shell: docker start {{ container.Names }}
    entity: container
    trigger: Update container entity file

  - title: Stop {{ container.Names }}
    icon: <iconify-icon icon="line-md:lightbulb-off-loop"></iconify-icon>
    timeout: 100
    shell: docker stop {{ container.Names }}
    entity: container
    trigger: Update container entity file

  - title: Update container entity file
    shell: 'docker ps -a --format json > /etc/OliveTin/entities/containers.json'
    hidden: true
    execOnCron: '*/5 * * * *'
    acls:
        - "cron"

entities:
  - file: /etc/OliveTin/entities/containers.json
    name: container

dashboards:
  - title: Docker Containers
    contents:
      - title: 'Container {{ container.Names }} ({{ container.Image }})'
        entity: container
        type: fieldset
        contents:
          - type: display
            title: |
              {{ container.RunningFor }} <br /><br /><strong>{{ container.State }}</strong>
          - title: 'Start {{ container.Names }}'
          - title: 'Stop {{ container.Names }}'

```
