### ISSUE TITLE
Rate limit per entity

### ISSUE THREAD

**Issue by okgolove** [OliveTin/OliveTin#543]
**Is your feature request related to a problem? Please describe.**
I have multiple actions which restarts services. I would like to use entities to generate actions and prevent users from clicking restart too often (using rate limit). The problem is rate limit affects action, not action per entity.

**Describe the solution you'd like**
It would be great to have separate rate limits per action <-> entitiy.

**Additional context**
config example:
```yaml
actions:
  - title: 'Restart {{ services.name }}'
    shell: 'systemctl restart {{ services.name }}'
    timeout: 10
    icon: 🔄
    entity: services
    maxConcurrent: 1
    maxRate:
      - limit: 1
        duration: 5m

entities:
  - file: /config/services.yaml
    name: services
```

services.yaml:
```yaml
- name: monitoring
- name: pinger
- name: pinger2
- name: httpd
```

So you will receive 4 actions:
- Restart monitoring
- Restart pinger
- Restart pinger2
- Restart httpd

Running, for example, `Restart pinger` should not prevent running `Restart httpd` because of rate limit.
