### ISSUE TITLE
Arch AUR Packages

### ISSUE THREAD

**Issue by jamesread** [OliveTin/OliveTin#55]
I'd like to start packaging OliveTin for various Linux distributions, and given that Arch is popular, but is unable to use .rpm, and .deb formats already created by the project, I thought I'd start with that. I've been hacking for a few hours today, and created my first Arch package. :-) 

Install with `yay -Syu olivetin`. 
Arch AUR: https://aur.archlinux.org/packages/olivetin
Base repo: https://github.com/OliveTin/package-arch-aur

In trying to install the package with `yay`, I then found that @AlphaJack has created `olivetin-bin` already - thanks @AlphaJack! Wish I saw that before, I didn't mean to get in the way of what you were doing, thanks for packaging OliveTin :-) 

I can see your package uses the binary packages - that's actually pretty cool, and useful. I think both packages can remain?

**Comment by AlphaJack** [comment]
Yes, it's up to the user to trust the already built binaries provided by the developer or compile everything from scratch.   
The two PKGBUILD should 

- package the same file list
- be marked as incompatible with with each other, in order to avoid errors when unpackaging them
    - see the "provides=()" array
    - see the "conflicts=()" array

**Comment by jamesread** [comment]
Hey @AlphaJack , thanks for taking the time to reply here, and again thanks for taking the initiative and creating `olivetin-bin` for Arch. It's certainly useful to have a re-packaging of the "official" binaries, as well as building natively on Arch. Let's keep both packages then - as they are both useful.

I've got a couple of questions if that's OK - so the packages can co-exist nicely :-) 

1. Shall we agree to both set `provides=('olivetin')`, and `conflicts=('<other package>')` ? I'm happy to do that. 
2. I've documented your package here - https://docs.olivetin.app/install-archbtw.html - are you happy with that description? 
3. What's your preferred way for me to raise issues against `olivetin-bin` (if there are any issues in the future?). Is there anywhere you'd accept PRs (don't think any are necessary right now, but possibly for the future). I think it would be good to call that out at docs.olivetin.app. 
4. Do you intend to update the package for the recent 2022-04-07 release?

Thanks again for your time!

**Comment by AlphaJack** [comment]
1. yes, already did yesterday
2. I would revise paths and the systemd unit casing to comply better with other arch linux packages:
    - as you already saw and patched, there is no /usr/local/bin
    - there is no /var/www/, I've placed webui files in /usr/share/webapps/olivetin/webui/, as other webapps use  /usr/share/webapps/
    - I've (personally) stylized olivetin in lowercase for both the binary file, systemd unit, configuration path and webui directory, This offers better consistency with 99% of the other packages from both the official repos and the aur, people expect to install packages in lowercase and find their unit/binary/configuration path in lowercase too. NetworkManager.service is really the only exception I can think, but everything else is in lowercase. What do you think?
    - I can make you co-author of the -bin package if you'd like to, so you can keep both versions updated at the same time.
3. I receive mails from both the AUR page comments and when you mention me here
4. yes, already did yesterday

Additional things:

- I think you misspelled the date in your aur package, inverting the month and the day
- Kudos for the configdir flag, what do you think of the olivetin@.service I'm shipping? It allows to run olivetin as an unprivileged user by starting olivetin@user.service, loading its coniguration file from /etc/olivetin/user/config.yaml

**Comment by jamesread** [comment]
@AlphaJack So sorry that I've been AWOL for a while - I've had a very busy few months!

I'll reply to the rest of the issues shortly, just wanted to highlight a change made in #68 that affects you, hopefully positively - removing the package version from the filename means this URL *should* always work for the future; https://github.com/OliveTin/OliveTin/releases/latest/download/OliveTin-linux-amd64.tar.gz (and similar packages/archives too, of course).

**Comment by jamesread** [comment]
@AlphaJack I've updated my package to properly conflict with yours. 

The last issue is solve here is now is in your olivetin-bin, the version "number" scheme of OliveTin has now switched to using the more standard "." instead of "-" in the version name. This means you can remove the find/replace on the version name for future versions in your package.

**Comment by mcurly** [comment]
@jamesread Hello.

I have been trying to build your package.

Today, it fails at 

```
go install "google.golang.org/protobuf/cmd/protoc-gen-go"
buf generate
make: buf: The file or folder does not exist
make: *** [Makefile:38: grpc] Error 127
```
and @AlphaJack 

Your package installs alriight but it fials to start the service `olivetin.service: Start request repeated too quickly.`

Can any of you lend some pointers to what might be happening here?

Thank you in advance

**Comment by AlphaJack** [comment]
@mcurly  I just updated the package to 2023.12.21, but I cannot reproduce your issue

@jamesread I see that now there is an official AUR package from you, but it is not automatically updated when you release a new version on Github

**Comment by mcurly** [comment]
> @mcurly I just updated the package to 2023.12.21, but I cannot reproduce your issue

Hello and thank you for your answer. Well I tried to install OliveTin, but it failed to compile if I was using a remote secure shell connection with no other parameters. The signing of the packages merely did not succeed. But, it did succeed when using `-XYC` parameters for the secure shell connection.
Can you please comment on that, @AlphaJack?

Thanks a bunch!

**Comment by mcurly** [comment]
@AlphaJack 

**This is an update**

Well, I was finally able to install and run the `olivetin-bin` version.

The provided systemd file made it impossible to run the provided service. I had to comment out the `Restart=always` _"stanza"_ to make it work.

Now it is finally working as expected.

Only _one_ thing missing though :sun_behind_small_cloud: :

If you can, please explain why the package was failing to compile from a secure shell headless connection. Do you happen to have hints on this?

Thank you!

**Comment by AlphaJack** [comment]
@mcurly I cannot reproduce your issue, for me it works as expected

**Comment by jamesread** [comment]
@mcurly , OliveTin is likely restarting quickly if it cannot find a config file. Can check the OliveTin logs from startup?

**Comment by mcurly** [comment]
Hello @jamesread and @AlphaJack .

I am sorry for this late response.

Can any of you answer if using the "given" "default" `config.yaml` file, one would expect the server/service not to start and even return those kinds of errors that I mentioned [here](https://github.com/OliveTin/OliveTin/issues/55#issuecomment-1901108766)?

I think I have nailed the spot for that. (keep on reading please).

Today, just to figure out what might be happening with the impossibility of running the server with those 'nagging' return codes stating that there were too many errors like these:

```
(...) olivetin.service: Scheduled restart job, restart counter is at 5.
(...) systemd[1]: olivetin.service: Start request repeated too quickly.
(...) systemd[1]: olivetin.service: Failed with result 'exit-code'.
(...) systemd[1]: Failed to start OliveTin. 

```

... I did a mixture of my own config.yaml file with the default one. (just to debug, I mean).

This is my current `config.yaml` file:

```

actions:
  - title: reiniciar servidor
    icon: "&#9212;"
    shell: systemctl reboot
    arguments:
      - type: confirmation
        title: Tem a certeza?!

  - title: desligar servidor
    icon: "&#128559;"
    shell: systemctl poweroff
    arguments:
      - type: confirmation
        title: Tem a certeza?!



# There is a built-in micro proxy that will host the webui and REST API all on
# one port (this is called the "Single HTTP Frontend") and means you just need
# one open port in the container/firewalls/etc.
#
# Listen on all addresses available, port 1337
#listenAddressSingleHTTPFrontend: 0.0.0.0:1337

# Choose from INFO (default), WARN and DEBUG
#logLevel: "INFO"

# Actions (buttons) to show up on the WebUI:
  - title: date
    shell: date
    popupOnStart: true

# This will run a simple script that you create.
#  - title: Run backup script
#    shell: /opt/backupScript.sh
#    shellAfterCompleted: "apprise -t 'Notification: Backup script completed' -b 'The backup script completed with code {{ exitCode}}. The log is: \n {{ stdout }} '"
#    maxConcurrent: 1
#    icon: backup
  
    # This will send 1 ping (-c 1)
    # Docs: https://docs.olivetin.app/action-ping.html
  - title: Ping host
    shell: ping {{ host }} -c {{ count }}
    icon: ping
    timeout: 100
    arguments:
      - name: host
        title: host
        type: ascii_identifier
        default: example.com
        description: The host that you want to ping
  
      - name: count
        title: Count
        type: int
        default: 1
        description: How many times to do you want to ping?
  
    # Restart lighttpd on host "server1"
    # Docs: https://docs.olivetin.app/action-ping.html
    #  - title: restart httpd
    #    titleAlias: restart_httpd
    #    icon: restart
    #    shell: ssh root@server1 'service httpd restart'
    #  
    # OliveTin can run long-running jobs like Ansible playbooks.
    #
    # For such jobs, you will need to install ansible-playbook on the host where
    # you are running OliveTin, or in the container.
    #
    # You probably want a much longer timeout as well (so that ansible completes).
    #  - title: "Run Ansible Playbook"
    #    icon: "&#x1F1E6"
    #    shell: ansible-playbook -i /etc/hosts /root/myRepo/myPlaybook.yaml
    #    timeout: 120
    #  
    # OliveTin can control containers - docker is just a command line app.
    #
    # However, if you are running in a container you will need to do some setup,
    # see the docs below.
    #
    # Docs: https://docs.olivetin.app/action-container-control.html
    #  - title: Restart Docker Container
    #    icon: restart
    #    shell: docker restart {{ container }}
    #    arguments:
    #      - name: container
    #        title: Container name
    #        choices:
    #          - value: plex
    #          - value: traefik
    #          - value: grafana
    #  
    #  - title: Slow Script
    #    shell: sleep 3
    #    timeout: 5
    #    icon: "&#x1F971"
    #  
    #  - title: Broken Script (timeout)
    #    shell: sleep 5
    #    timeout: 5
    #    icon: "&#x1F62A"

# see https://docs.olivetin.app/hide-nav.html
ShowNavigation: true
ShowFooter: true

# see https://docs.olivetin.app/network-ports.html
listenAddressRestActions: localhost:1338
listenAddressGrpcActions: localhost:1339
listenAddressWebUI: localhost:1340

# see https://docs.olivetin.app/update-tracking.html
checkForUpdates: true
showNewVersions: true


```

(Just as a sidenote, this `config.yaml` file gets parsed and the `olivetin.service` starts ok. I guess that the pounding signs do make a difference here in commenting out the commands that are not available on the underlying system).

It might be important to underline the fact that one cannot use the default `config.yaml` file as is. Perhaps, one should tailor it, not only to his/her own needs but to the possibilities of the system where the `olivetin.service` will run.

What I believe is happening is that the `config.yaml` file would only be correctly parsed out if the system where those commands would be executed would allow for those commands to run.

Does this make sense to you @jamesread  and @AlphaJack ?

I mean that the service only starts if the commands would be somewhat 'sane' ...

About [this other question](https://github.com/OliveTin/OliveTin/issues/55#issuecomment-1901018402) 
Does anyone ever encountered such an issue? What could have caused this? Can anyone reference anything about this? Thanks

That's all for now.

:sunny:
