### ISSUE TITLE
Allow regex specified custom string validation

### ISSUE THREAD

**Issue by strazto** [OliveTin/OliveTin#56]
From https://github.com/OliveTin/OliveTin/issues/42#issuecomment-1060045024 

**Is your feature request related to a problem? Please describe.**

We want to avoid allowing the `very_dangerous_raw_string` input type, and impose restrictions on allowed characters and patterns, however the input constraints change from application to application, for example, URLs have different requirements to other strings.

Though having some built-in defaults to cover common use-cases makes a lot of sense (int, uint, ascii, ascii_sentence, url, etc) there may be more complex patterns that require custom logic, eg, `dttm: YY-MM-DD hh:mm` , etc. 

**Describe the solution you'd like**

Allowing users to specify regex validation patterns in their configuration, (and maybe also a message format hint) might be a good way to accomodate this, for example:

https://github.com/OliveTin/OliveTin/issues/42#issuecomment-1060045024 

> It would be great to have an option to set a regex for string validation, like:
> 
> ```yaml
>         arguments:
>           - name: message
>             type: regex
>             regex: [a-z0-9:/.-]+
> ```

**Describe alternatives you've considered**

There might be other mechanisms to configure safe, customizable string escaping + validation, but I do think this is probably the most flexible + intuitive way to allow this.

**Additional context**

I also think there should be an optional config option for input format hints, which are displayed on the front-end, both for custom types and for the built-in types, eg:

[Taken from regextester](https://www.regextester.com/1966)

```yaml
        arguments:
          - name: Datetime
            type: regex
            regex: '^\d\d\d\d-(0?[1-9]|1[0-2])-(0?[1-9]|[12][0-9]|3[01]) (00|[0-9]|1[0-9]|2[0-3]):([0-9]|[0-5][0-9]):([0-9]|[0-5][0-9])$'
            hint: 'YYYY-MM-DD HH:MM:SS'
```

The equivalent for a builtin, say, `int`:

```yaml
        arguments:
          - name: Some int
            type: regex
            regex: '^[0-9]+$'
            hint: 'A positive integer'
```

This might render as:

```html
<p>
    <label for="some-int">Some int:</label>
    <input name="some-int" aria-describedby="some-int-desc">
    <span id="some-int-desc">A positive integer</span>
</p>
```

https://www.w3.org/WAI/tutorials/forms/instructions/

https://medium.com/nextux/form-design-best-practices-9525c321d759 

Or just put the hint in the placeholder
