### ISSUE TITLE
Logs Page Fails with GRPC Size Limit Error

### ISSUE THREAD

**Issue by NHZEX** [OliveTin/OliveTin#589]
**Describe the bug**
When executing commands that generate large output volumes, the Logs page fails to display results and returns a gRPC size limit error (max message size exceeded).

**To Reproduce**
1. Execute any command that produces substantial output
2. Navigate to the Logs page
3. Observe the error instead of command output

**Expected behavior**
Successfully display all logs

**Screenshots**

![Image](https://github.com/user-attachments/assets/2918d241-8953-4c06-91cd-0ce9130852af)

![Image](https://github.com/user-attachments/assets/6514c1e8-96b5-469b-a616-0ad8d61a2c5b)

```json
{
    "code": 8,
    "message": "grpc: received message larger than max (6239764 vs. 4194304)",
    "details": []
}
```

**Additional context**
- Version: 2025.4.22

**Comment by NHZEX** [comment]
> That looks very odd, why do you have logs & diagnostics repeated many times? Weird.

I might have discovered the cause of this issue. My network environment isn't very stable, with frequent disconnections. I noticed that after multiple disconnections and reconnections, the logs & diagnostics menu items keep accumulating

**Comment by NHZEX** [comment]
> grpc: received message larger than max

I've observed this error isn't necessarily caused by a single long task. If the combined size of all logs currently in the logs list is large enough, it can trigger this error. When this happens, I must restart the service to restore normal operation.

**Comment by jamesread** [comment]
Hey @NHZEX , I found that the multiple logs/diagnostics links were cause by lots of disconnects and reconnects. I patched that in 2025.6.6. 

Indeed, gRPC has a maximum size of a few mb for the entire message - I put a small workaround in OliveTin to limit logs to 10 executions as a time, but do some of your actions have a /lot/ of output?

**Comment by NHZEX** [comment]
Yes, some of my actions have a /lot/ of output.​​
Current implementation stores all output in memory? Should it be a rolling buffer?

**Comment by jamesread** [comment]
@NHZEX , I think that on reflection, this is less likely that I'd fix this in 2k now, and would probably only do a fix in 3k, if it's still happening there.

Would you mind upgrading to 3k and see if this is still an issue for you?

**Comment by NHZEX** [comment]
I upgraded from version 2025.6.22 to 3000.2.1 using the OliveTin_linux_amd64.deb.
After the upgrade, I cannot access the login page and encounter the following error:
### Log
```
api/olivetin.api.v1.OliveTinApiService/Init 403 (Forbidden)
Failed to Initialize OliveTin
Error Message: [permission_denied] guests are not allowed to access the dashboard

Please check the your browser console first, and then the server logs for more details.
```
### Config
```yml
authRequireGuestsToLogin: true
authLocalUsers:
  enabled: true
  users:
    - username: ******
      usergroup: admins
      password: ******

accessControlLists:
  - name: admins
    matchUsergroups:
      - admins
    policy:
      showDiagnostics: true
      showLogList: true
    permissions:
      view: true
      exec: true
      logs: true
    addToEveryAction: true

defaultPolicy:
  showDiagnostics: false
  showLogList: false
```

**Comment by a-bezruchenko** [comment]
tldr: I cannot reproduce the bug in current version. NHZEX, try setting "authRequireGuestsToLogin" to false in config and it will work just like old version but without the gRPC bug. You can set name and password later if you want, it is not required. 



I was greatly annoyed by this bug, so here is minimal config for reproduction on olivetin 2025.4.22:

```yaml
listenAddressSingleHTTPFrontend: 0.0.0.0:1337
logLevel: "INFO"
checkForUpdates: false
actions:
  - title: Generate 10 bytes
    id: gen_10b
    shell: tr -dc 'A-Za-z0-9' < /dev/urandom | head -c 10 | cat
    icon: smile
    timeout: 5

  - title: Generate 3 MB
    id: gen_3mb
    shell: tr -dc 'A-Za-z0-9' < /dev/urandom | head -c 3M | cat
    icon: smile
    timeout: 5

  - title: Generate 6 MB
    id: gen_6mb
    shell: tr -dc 'A-Za-z0-9' < /dev/urandom | head -c 6M | cat
    icon: smile
    timeout: 5

  - title: Restart olivetin
    id: restart_olivetin
    shell: systemctl restart --now OliveTin
    icon: smile
    timeout: 1
```

Open main page in one tab, log page in other tab.

If you click only "generate 10 bytes" button, everything works correctly - new entries are added to log until the limit of 10 entries, then clicking on the button deletes one old log entry to make space for new one.

If you click "generate 3 MB" button twice, log page shows two entries, but they disappear after reloading page, and any new entries (including 10 bytes) are not shown. To fix it, you need to either "generate 10 bytes" 10 times or restart olivetin.

If you click "generate 6 MB" button once, log page shows one entry, but it disappears after reloading page, and any new entries (including 10 bytes) are not shown. Sometimes it also shows "Too Many Requests" error, but sometimes it doesn't (i cannot understand the logic, but it doesn't seem to happen with 3 MB). To fix it, you need to either "generate 10 bytes" 10 times or restart olivetin.

After upgrading to 3000.7.0, you need to change config a bit:
```yaml
listenAddressSingleHTTPFrontend: 0.0.0.0:1337
logLevel: "INFO"
checkForUpdates: false
actions:
  - title: Generate 10 bytes
    id: gen_10b
    shell: tr -dc 'A-Za-z0-9' < /dev/urandom | head -c 10 | cat
    icon: smile
    timeout: 5

  - title: Generate 3 MB
    id: gen_3mb
    shell: tr -dc 'A-Za-z0-9' < /dev/urandom | head -c 3M | cat
    icon: smile
    timeout: 5

  - title: Generate 6 MB
    id: gen_6mb
    shell: tr -dc 'A-Za-z0-9' < /dev/urandom | head -c 6M | cat
    icon: smile
    timeout: 5

  - title: Restart olivetin
    id: restart_olivetin
    shell: systemctl restart --now OliveTin
    icon: smile
    timeout: 1

authRequireGuestsToLogin: false
```

In this version, bug no longer reproduces (but it takes a long time to load the log page and at first it may look like entries disappeared).
