### ISSUE TITLE
Warning in logs for /api/readyz endpoint when authHttpHeaderUsername is configured

### ISSUE THREAD

**Issue by okgolove** [OliveTin/OliveTin#592]
**Describe the bug**
A warning appears in the logs for the readyz endpoint when authHttpHeaderUsername is configured. This is mostly about Kubernetes (because of liveness and readiness checks).

**To Reproduce**
1. Install OliveTin via helm chart in Kubernetes with values:
```yaml
olivetin:
  config:
    rawYaml:
      authHttpHeaderUsername: "X-Auth-Request-Email"
      actions:
        - title: "Hello world!"
          shell: echo 'Hello World!'
```
2. Send a HTTP request with X-Auth-Request-Email - no warnings are expected.
3. Just wait for yet another liveness/readiness checks, then check logs:

```
WARN Config has AuthHttpHeaderUsername set to X-Auth-Request-Email, but it was not found
```

**Expected behavior**
No warnings in logs, the pod is healthy.
