### ISSUE TITLE
Using dashboards buttons are not fully hidden when using ACLs

### ISSUE THREAD

**Issue by rabid-dev** [OliveTin/OliveTin#598]
**What seems to be the problem?!**

Using dashboards buttons are not hidden using ACLs

If I use acls but no dashboards, buttons are invisible just as expected

However when using dashboards if a user doesn't have permission to execute a button it will render a red button that says "Action not found" revealing that there is indeed one action with that name

![Image](https://github.com/user-attachments/assets/e3a1c803-926e-4155-b589-9b820b9c8ce4)

**Can you provide a sosreport?**

Can't because the link is broken

**What package/file/container did you use to install OliveTin?**

2025.6.1

**Your config.yaml**

```
actions:
  - title: "Ping Server A"
    shell: ping -c 5 servera
    acls:
      - admin
      - bob
  - title: "Ping Server B"
    shell: ping -c 5 serverb
    acls:
      - admin

dashboards:
  - title: dashboard
    contents:
      - title: 💎 cool 💎
        type: fieldset
        contents:
          - title: "Ping Server B"
          - title: "Ping Server A"

accessControlLists:
  - name: admin
    matchUsergroups:
      - admin
    policy:
      showDiagnostics: true
      showLogList: true
    permissions:
      view: true
      exec: true
  - name: bob
    matchUserNames:
      - bob
    policy:
      showDiagnostics: false
      showLogList: false
    permissions:
      view: true
      exec: true

defaultPermissions:
  view: false
  exec: false
  logs: true
```

**OliveTin logs**

No error no need to logs

**Screenshot of WebDeveloper console logs**

Not relevant

**Anything else?**

N/A
