### ISSUE TITLE
Empty dashboards when using fieldsets

### ISSUE THREAD

**Issue by yamek** [OliveTin/OliveTin#603]
**Describe the bug**
Actions inside dashboard fieldset are not being considered when checking if a dashboard is empty. As a result, the dashboard is hidden and all actions are displayed in the general "Actions" section. Also and probably because of the same issue, when mixing actions in the dashboard root contents node with fieldset ones, the dashboard appears with the root actions only and the rest go to the "Actions" section.

**To Reproduce**
```yaml
dashboards:
  - title: Test
    contents:
      # Uncomment to see the dashboard with the "Ping" action only
      # - title: Ping
      - title: Fieldset 1
        type: fieldset
        contents:
          - title: Action 1
          - title: Action 2
      - title: Fieldset 2
        type: fieldset
        contents:
          - title: Action 3
          - title: Action 4
```

**Additional context**
Version 2025.6.6: fix: Empty dashboards are hidden (https://github.com/OliveTin/OliveTin/pull/599)

**Comment by jamesread** [comment]
Heya, just a quick note so say I acknowledge this is a bug introduced in the last release, and that really frustrates me - as I'm sure it does for you - I'm sorry about that. I really try hard not to break configs in upgrades. 

The root cause of the bug is that I tried to fix another issue of showing "broken" dashboards if the user doesn't have permissions to see anything on that dashboard. So now dashboards are filtered before they are sent to ghe browser. Fieldsets with entities still work, but fieldsets without entities are parsed differently, and they are being removed. 

I've not fixed it yet for 2 reasons: 

1) I'm super excited about a new project - Japella ( https://github.com/jamesread/japella ) and I've been sinking huge amounts of my free time into that over the last 2 weeks. 

2) I'm really keen to make some big upcoming changes to OliveTin that I know a lot of people will like, but, I need to do that in a way that doesn't bteak people's setups (like this). So I need to invest more time into developing test cases and doing regression testing smartly, which is why I don't want to necessarily just issue a quick hotfix here. 

Lastly, I did spend 2 hours trying to navigate and code on my phone this evening while I've taken my whole family to my parents house this evening... And even patching simple issues like this, on a phone, isn't fun! 

So, please be reassured you're not being ignored, and I'll issue a fix for this as soon as I'm able.

**Comment by yamek** [comment]
Hi there, thank you for your reply (and for OliveTin ;) ). 
Take your time, it is not a big issue and we can still use the previous version if the dashboard layout is really important for the use case (I personally use OliveTin API the most).
Thanks again and no coding while on the phone :)

**Comment by yamek** [comment]
This one can be closed as far as I'm concerned.

PS: I saw something weird when using entities in fieldset with one action only (no type: display). But I haven't had the time to confirm it. Should be a different issue anyways. Thank you

**Comment by norsemangrey** [comment]
I am seeing some weird behavior on the current version (2025.7.29) which might be related. I am not able to create folders at all....that is, whenever I try to create folders, all my actions are shown on the Actions dashboard and the dashboard with the folder(s) is hidden.

```
actions:
  - title: Action 1
    shell: echo "Action 1 executed"
    timeout: 10
  - title: Action 2
    shell: echo "Action 2 executed"
    timeout: 10
  - title: Action 3
    shell: echo "Action 3 executed"
    timeout: 10
  - title: Action 4
    shell: echo "Action 4 executed"
    timeout: 10

dashboards:
  - title: Test
    contents:
      - title: Folder 1
        contents:
          - title: Action 1
          - title: Action 2
      - title: Folder 2
        contents:
          - title: Action 3
          - title: Action 4
```
