### ISSUE TITLE
Child Processes not being cleaned up on Timeout

### ISSUE THREAD

**Issue by TheDerpySage** [OliveTin/OliveTin#605]
**What seems to be the problem?**

I have a program that doesn't seem to play nice with the signal being sent by timeout. When timeout fires, the inital `sh -c` process is terminated but it leaves the child processes. 

I did attempt to add a `trap` to a bash script making the call, but this also doesn't seem to work because timeout leaves the child bash.

My use case is I'm using OliveTin to launch videos on my TV connected Raspberry Pi. Between streams and set-length videos, neither case obeys Timeout.

The funny thing is that I can go to Logs after the timeouts past, and I can see it still technically running. When I hit Kill, the child processes are killed, and it says the process timed out.

**What package/file/container did you use to install OliveTin?**

OliveTin_linux_arm64.deb
`commit="b2e7509" date="2025-06-01T11:51:17Z" version="2025.6.1"`

**Your config.yaml**

The relevant block, running mpv targeting the open display session.
```
- title: Watch TV
    icon: 📺
    shell: XAUTHORITY=/var/run/lightdm/root/:0 DISPLAY=:0 mpv --terminal=no --profile=low-latency --fs "{{ CHANNEL }}"
    arguments:
      - name: CHANNEL
        [...]
    maxConcurrent: 1
    timeout: 21600
    popupOnStart: execution-dialog
```

**Anything else?**

I saw this suggestion in another [issue,](https://github.com/OliveTin/OliveTin/issues/328#issuecomment-2174019153) I think I would appreciate being able to specify the signal being sent by timeout, if there's no other way to enforce the child processes also close with the parent.
