### ISSUE TITLE
Entity variable resolution apply to more action fields

### ISSUE THREAD

**Issue by rabid-dev** [OliveTin/OliveTin#606]
**Is your feature request related to a problem? Please describe.**
I just thought it would be nice to be able to use the variables defined within entities in other action fields, because as of today, you can only use these on the "Action title" and the "Action shell"

**Describe the solution you'd like**
For example given this entity file

```
{ "name" : "machine1", "permission" : "departmentA", "icon" :  "🦖" }
{ "name" : "machine2", "permission" : "departmentB", "icon" :  "🐘" }
```

And these actions
```
actions:
  - title: Action for {{ machines.name }}
    icon: 👍 {{ machines.icon }}
    shell: echo "good morning {{ machines.name }}"
    acls: {{ machines.permission }}
    entity: machines
```

And it would resolve to this:
```
actions:
  - title: Action for machine1
    icon: 👍 🦖
    shell: echo "good morning machine1"
    acls: departmentA
    entity: machines

  - title: Action for machine2
    icon: 👍🐘
    shell: echo "good morning machine2"
    acls: departmentB
    entity: machines
```
