### ISSUE TITLE
Triggers - Passing arguments from main action to the called action

### ISSUE THREAD

**Issue by accforgithubtest** [OliveTin/OliveTin#607]
I am looking for help / suggestions on how I might be able to get this working -
1. I have an action that lets user select a drop down
2. This action does something, and then calls another action via `triggers`

I want to be able to pass the user selection from the drop down in first action to the second action.
How can I do this ?

This below example allows me to use action A and Action B independently and thats working fine. 
I also want to be able to run the `Multiple Actions` action with the same drop downs, but be able to pass the user selections to actions A & B from `Multiple actions` by using triggers.

If I dont specify the `{{ userathost }}` part in the `triggers` section of `Multiple Actions`, I get error
```
Required arg not provided: userathostRequired arg not provided: userathost
```

When I specify `{{ userathost }}` as below, I see the error -
```
Action not found: Action A {{ userathost }}
```

```
- title: Action A
  id: action_a
  icon: "&#128640;"
  shell: ssh {{ userathost }} 'echo aaaaaa'
  popupOnStart: execution-dialog
  timeout: 100
  arguments:
    - name: userathost
      title: Select Device
      entity: ubuntu_servers
      choices:
        - title: '{{ ubuntu_servers.name }}'
          value: '{{ ubuntu_servers.uid }}@{{ ubuntu_servers.ip }}'

- title: Action B
  id: action_b
  icon: "&#129529;"
  shell: ssh {{ userathost }} 'echo bbbbbb'
  popupOnStart: execution-dialog
  timeout: 100
  arguments:
    - name: userathost
      title: Select Device
      entity: ubuntu_servers
      choices:
        - title: '{{ ubuntu_servers.name }}'
          value: '{{ ubuntu_servers.uid }}@{{ ubuntu_servers.ip }}'

- title: Multiple Actions
  id: actions_a_b
  icon: "&#128640;&#129529;"
  shell: echo cccccc
  popupOnStart: execution-dialog
  timeout: 100
  arguments:
    - name: userathost
      title: Select Device
      entity: ubuntu_servers
      choices:
        - title: '{{ ubuntu_servers.name }}'
          value: '{{ ubuntu_servers.uid }}@{{ ubuntu_servers.ip }}'
  triggers:
    - Action A {{ userathost }}
    - Action B {{ userathost }}

```

I appreciate your help  / suggestions, cheers !
