### ISSUE TITLE
Add action confirmation

### ISSUE THREAD

**Issue by jamesread** [OliveTin/OliveTin#69]
Originally requested by "Wouter" over email.

**Is your feature request related to a problem? Please describe.**
"Are you sure?" type confirmation before executing an action.

I could easily add an argument type: "hidden" to do this easily.

```
- title: Ask for confirmation
  shell: lscpu
  arguments:
    - name: confirmation
      type: hidden
```

**Comment by bebebjorn** [comment]
Hi, I am new to OliveTin but it looks great!
I would love this confirm feature and also grouping/folders for tasks (and a header icon, home button)
Was this "type: hidden" argument available already?

I have solved it for my usage by coding it this way for example:

```
- title: "Server Update Tasks"
  timeout: 3600
  icon: "&#9749;"
  shell: bash -c 'if [[ "{{ confirm }}" == "yes" ]];then echo "Running Command [{{ tasks }}]...";{{ tasks }};else echo "The user input [{{ confirm }}] was not expected. Operation cancelled";fi;'

  arguments:
  - name: confirm
    title: Confirm
    type: very_dangerous_raw_string
    default: 'yes / no'
  - name: tasks
    choices:
    - title: "Update All Servers"
      value: /scripts/update/update_all.sh
    - title: "Check and Reboot All Servers"
      value: /scripts/update/check_reboot_all.sh
    - title: "Autoremove On All Servers"
      value: /scripts/update/autoremove_all.sh
```

This is however a bit dangerous, using the "very_dangerous_raw_string".

Keep up the good work :)
