### ISSUE TITLE
Configuration parameter "showNavigation" and "showFooter" ignored

### ISSUE THREAD

**Issue by ManOki** [OliveTin/OliveTin#72]
**Describe the bug**
If I set `showNavigation: false` or `showFooter: false`, the corresponding elements are still shown. [Documentation](https://docs.olivetin.app/toggle-webui.html)

**Additional context**
I use the [latest docker image](https://hub.docker.com/r/jamesread/olivetin) (i.e., 2022-04-07) with an apache2 reverse proxy. `externalRestAddress` is properly configured, the action buttons run fine.

I even tested logLevel DEBUG, the configuraton is read correctly.

The `hideNavigation: true` parameter in the previous docker image 2022-01-06 did also work as expected.

**Comment by jamesread** [comment]
Hey, thanks for reporting this. I've been a bit limited on time recently, but I'll take a look as I'm catching up on a bunch of OliveTin stuff.

**Comment by jamesread** [comment]
Hey @ManOki , I just checked the 2022-04-07 release - there is an integration test for this actually, which is currently passing. 

Here's the config I'm testing which works. 

```
showNavigation: false
showFooter: false

logLevel: "DEBUG"

actions:
  <snip>
```

Could you share me the config file that you're using where this isn't working for you?

**Comment by ManOki** [comment]
Still not working on latest docker image 2022.11.14

My config is:

```
logLevel: "INFO"

#externalRestAddress: https://server.com/nas

showFooter: false
showNavigation: false
checkForUpdates: false
showNewVersions: false

actions:
  - title: "Ping NAS"
    shell: ssh -tt user@server 'timeout 1 ping nas -c 1'
    icon: ping
    timeout: 2
  - title: "Start NAS"
    shell: ssh -tt user@server '/usr/bin/wakeonlan XX:XX:XX:XX:XX:XX'
    icon: "&#9211;"
    timeout: 5
```
