### ISSUE TITLE
Add option for displays

### ISSUE THREAD

**Issue by TheRaven500** [OliveTin/OliveTin#73]
It would be nice to have not only buttons but also displays (hope this is the right word?).
Example:
A raspberry pi with a temperatur sensor which writes the temperature to a file (lets say /tmp/kitchen).
In this file you have some text, lets say "21.5°C".
And then maybe something in config like:
```
displays:
- title: Kitchen-Temp
  icon: "&#127777;"
  file: /tmp/kitchen
  poll: 5

```
Poll grabs every X seconds (in this example 5) the value of the file and shows in webbrowser. Or maybe this is not needed because it refreshes it selves?
And of course, there are many other situations which you can use this to show some statuses (light on/off, show water tank level...)
Example (icon 1):
![olivetin](https://user-images.githubusercontent.com/63654062/191801088-45453dcf-273f-4819-8aff-757626e719cb.jpg)
