### ISSUE TITLE
'restart' icon displays incorrectly

### ISSUE THREAD

**Issue by benfishbus** [OliveTin/OliveTin#75]
**Describe the bug**
The example config file references a built-in icon called 'restart' , but for me this displays as:
![image](https://user-images.githubusercontent.com/14032737/193067285-face1836-0489-4467-9e17-f83f32a9eb1a.png)

The 'ping' icon does display correctly:
![image](https://user-images.githubusercontent.com/14032737/193068887-852df8f0-ca47-4fd1-ae5d-45f025344fe5.png)

External icons also display correctly:
![image](https://user-images.githubusercontent.com/14032737/193069152-6d26cdd6-29ed-4635-97ab-9156a338f640.png)

My actions config:
```
actions:
- title: Restart Plex
  icon: '<img src = "https://www.plex.tv/wp-content/uploads/2018/01/pmp-icon-1.png" width = "48px"/>'
  shell: docker restart PlexMediaServer
  timeout: 10
  
- title: Ping host
  shell: ping {{ host }} -c {{ count }}
  icon: ping
  arguments:
    - name: host
      title: host
      type: ascii_identifier
      default: example.com

    - name: count
      title: Count
      type: int
      default: 1
  
- title: restart httpd
  icon: restart
  shell: ssh root@webserver1 'service httpd restart'
```
